### ISSUE TITLE
Overly high memory consumption after data download

### ISSUE THREAD

**Issue by karpfen** [ropensci/osmdata#108]
Whenever I'm issuing a larger query, the `R` process' memory usage maxes out and stays there. The effect seems not to be caused by the size of the downloaded object, but by something that clutters up the RAM. Here's a little example:

```
ls () # nothing up my sleeves
# character(0)

query <- opq ("Berlin")
query <- add_osm_feature (query, key = "highway")
berlin_streets <- osmdata_sf (query)

object.size (berlin_streets)
# 17165660800 B

pryr::mem_used ()
# 3.23 GB

saveRDS (berlin_streets, "berlin.rds")
```
Memory usage according to `ps -aux`:
6553876 kB

---
**This is a new R session**
```
ls ()
# character(0)

berlin_streets <- readRDS ("berlin.rds")
object.size (berlin_streets)
# 17165660800 B

pryr::mem_used ()
# 3.23 GB
```
Memory usage according to `ps -aux`:
ps -aux
4729788 kB

The only way (to my knowledge) to get the allocated RAM back, is to quit R and start a new session. The `pryr::mem_used` results suggest that the additional memory is not used for the objects in the workspace. Is it possible that there is some memory leak in `osmdata` that is causing this effect?

Btw, I tried this on two machines:

- Ubuntu 16.04.3, R version 3.4.2, osmdata_0.0.5
- Debian 9, R version 3.4.2, osmdata_0.0.5.100

with each ~8GB RAM. Both with the same results.

**Comment by mpadge** [comment]
Results of
```
R -d "valgrind --tool=memcheck --leak-check=full" -f test.R
```
where `test.R` does a standard `osmdata_sf` call:
```
==8958== 
==8958== HEAP SUMMARY:
==8958==     in use at exit: 75,003,902 bytes in 54,366 blocks
==8958==   total heap usage: 141,885 allocs, 87,519 frees, 183,747,274 bytes allocated
==8958== 
==8958== LEAK SUMMARY:
==8958==    definitely lost: 0 bytes in 0 blocks
==8958==    indirectly lost: 0 bytes in 0 blocks
==8958==      possibly lost: 0 bytes in 0 blocks
==8958==    still reachable: 75,003,902 bytes in 54,366 blocks
==8958==         suppressed: 0 bytes in 0 blocks
==8958== Reachable blocks (those to which a pointer was found) are not shown.
==8958== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==8958== 
==8958== For counts of detected and suppressed errors, rerun with: -v
==8958== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
so it's not a memory leak. This made me also dig deeper and find out about the [`massif` tool](http://valgrind.org/docs/manual/ms-manual.html). The output of the following:
```
R -d "valgrind --tool=massif" -f test.R
msprint --threshold=10.0 massif.out.<pid>
```
seems to suggests that the main memory usage is in R vector allocations, but doesn't indicate any direct `osmdata` issues. Hmm...

**Comment by mpadge** [comment]
Check it: First save some OSM data:
```
opq (c (9.538, 51.288, 9.555, 51.294)) %>%
    add_osm_feature (key = "highway") %>%
    osmdata_xml (filename = "junk.osm")
```
Then quit R, start again and run this:
```
getmem <- function ()
{
    s <- system ("ps -aux | grep exec/R", intern = TRUE) [1]
    as.numeric (strsplit (s, "\\s+") [[1]] [6]) # the RSS col of ps aux = non-swapped physical memory
}
m <- NULL
m <- c (m, getmem ())
devtools::load_all (".", export_all = FALSE)
m <- c (m, getmem ())
dat <- opq (c (9.538, 51.288, 9.555, 51.294)) %>%
    add_osm_feature (key = "highway") %>%
    osmdata_sf (doc = "junk.osm")
m <- c (m, getmem ())
dat2 <- sf::st_read ("junk.osm", layer = "lines", quiet = TRUE)
m <- c (m, getmem ())
```
Then plot the results
```{r}
plot (seq (m), m)
lines (seq (m), m)
text (seq (m), m, labels = c ("R", "osmdata", "osmdata_sf", "sf"),
      pos = c (3, 2, 2, 2))
```
![junk](https://user-images.githubusercontent.com/6697851/33341914-9bcbe218-d480-11e7-836b-c07fe92e7e97.png)

`osmdata` actually uses less memory than `sf`! You can restructure it to run the two `osmdata_sf` and `sf::st_read` in two separate R sessions and it still gives pretty much the same results. Also, `osmdata` as usual is extracting a heap more data than `sf` - the latter only the `lines` layer, while `osmdata` extracts all five layers.

**Comment by mpadge** [comment]
another view on the issue: Run this for each of the two options in a new R session:
```
profil <- function (n = 10, sf = FALSE)
{
    m0 <- getmem ()
    m <- m2 <- rep (NA, n)
    for (i in 1:10)
    {
        if (sf)
            dat <- sf::st_read ("junk.osm", layer = "lines", quiet = TRUE)
        else
            dat <- opq (c (9.538, 51.288, 9.555, 51.294)) %>%
                add_osm_feature (key = "highway") %>%
                osmdata_sf (doc = "junk.osm")
        # rm (dat) # This makes no difference!!
        m [i] <- getmem () - m0
    }
    if (sf)
        save (m, file = "msf.rda")
    else
        save (m, file = "m.rda")
}
profil ()
#profil (sf = TRUE)
```
Then recombine and plot the results
```
load ("msf.rda")
msf <- m
load ("m.rda")
ylims <- range (c (m, msf))
plot (seq (m), m, "l", col = "blue", lwd = 2, ylim = ylims)
lines (seq (msf), msf, col = "red", lwd = 2)
legend ("bottomright", lwd = 2, col = c ("red", "blue"), bty = "n",
        legend = c ("sf", "osmdata"))
```

![junk](https://user-images.githubusercontent.com/6697851/33342790-96ec1f12-d483-11e7-848a-9277cbeac081.png)

I never even knew that **R** behaved like this, but `sf` ends up using nearly three times as much memory as `osmdata`, and `osmdata` increases way more conservatively at first. The really interesting thing is that `rm(dat)` makes no difference at all to memory usage. I guess this all just means there's no way to avoid having to restart a new **R** session for each iteration.

**Comment by richardellison** [comment]
Having run into this issue before (even with just reading some particularly large files), you can avoid a restart of R by running gc() to force R to release unused memory after an rm() or other memory intensive process.

**Comment by karpfen** [comment]
Wow, thanks for the insights! I wouldn't have thought that using `sf` makes such a difference.
Also thanks for the pointer to `gc`!
