### ISSUE TITLE
codemeta encoding for Maëlle

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#109]
@cboettig, @graceli8: I've put [`codemetar` stuff in `DESCR`](https://github.com/ropensci/osmdata/commit/d5b89a13d60f5202bbc6641f864f899a44b6c022) but `codemeta()` bails on `non-ASCII input in a CITATION file without a declared encoding.` (respect to @maelle for your continued insistence on living beyond the ASCII world!) Simply putting `encoding: "UTF-8"` in `CITATION` does not fix it. Any suggestions please?

**Comment by maelle** [comment]
Thanks and sorry. At the same time this is a good puzzle to solve for `codemetar` :angel:

**Comment by cboettig** [comment]
should be fixed in https://github.com/ropensci/codemetar/commit/2246fbab845bb2b640ced61ca2d6ed215895ae43 , sorry I let this slip!
