### ISSUE TITLE
Queries (curl) don't work on windows behind a corporate proxy

### ISSUE THREAD

**Issue by beingalink** [ropensci/osmdata#111]
I get following error:
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds
```
Perhaps this could be circumvented using the system proxy settings from internet explorer. Curl seems to have the functions `ie_proxy_info()` and `ie_get_proxy_for_url()` for that purpose.

**Comment by mpadge** [comment]
No, that's just because of the overpass server being overloaded. If you just re-try it - manually, not automatically! - you'll eventually get a response

**Comment by beingalink** [comment]
What do you mean by "manually"? At home I had no problems, at work I never got it to run without this error.

**Comment by mpadge** [comment]
By manually, I mean that you shouldn't write a loop to keep trying until it works. This is just a standard overpass server message. The overpass server has some very cool and complex ways to pre-estimate likely query sizes and prioritizes queries accordingly. If your work IP address is associated with lots of large queries, it'll likely be de-prioritized at the outset, which might be why you never encounter this at home.

**Comment by beingalink** [comment]
I was never using a loop, just the example code above. And I only know one other person here at work who uses overpass but not on a daily basis. To me this rather looks like the connection gets blocked as it's not using the global proxy (I assume). You seem to be pretty sure that it's not what I think it is and since I don't have much knowledge in this area, I'll just leave it as is. I'll reopen when I can provide some "hard facts". Thank you for your quick answers! I appreciate that.

**Comment by mpadge** [comment]
Of course you could be right that it is getting blocked by a proxy, but there do not appear to have been any windows exceptions since Feb 2016 (see the [`curl` master issue](https://github.com/jeroen/curl/issues/1)), so i suspect that's not likely the cause. I'd suggest investigating things further your side by first using `opq_string` to convert the `opq` object into the direct string passed to `overpass`, and then using basic [`curl` functionality](https://cran.r-project.org/web/packages/curl/vignettes/intro.html) to examine what happens during the `GET` - start with `curl::curl` or `curl::curl_fetch_memory`. Feel free to re-open this issue if you find any systematic problem here.

**Comment by beingalink** [comment]
OK, I'm quite sure now that this problem is about missing proxy settings.
```
con <- curl("https://httpbin.org/get")
readLines(con)
```
results in
```
Error in readLines(con) : 
  Failed to connect to httpbin.org port 443: Timed out
```
Giving proxy settings like this
```
h <- new_handle()
handle_setopt(h, proxy = "xxx:80", proxyuserpwd = "xxx:yyy")
con <- curl("https://httpbin.org/get", handle = h)
readLines(con)
```
makes it work fine.

**Comment by mpadge** [comment]
I see. I've called in some external advice here via [this rOpenSci question](https://discuss.ropensci.org/t/windows-proxy-settings/990), so keep your eyes on that for a solution.

**Comment by beingalink** [comment]
I found a workaround. It's not pretty but it works:
```
library("osmdata")
library("sf")
library("httr") # needed to set global httr config

# Set global proxy settings for httr/curl
set_config(use_proxy("proxyaddress", port = 80, username = "xxx", password = "yyy", auth = "basic"),
           override = TRUE)

dat <- opq ("deutschland") %>%
  add_osm_feature (key = "de:regionalschluessel", value = "^07", value_exact = FALSE) %>%
  osmdata_sf ()
```
I need to load the httr package myself to be able to set the proxy settings and I need to make these global. This solves the problem for me but it might be nicer to have a way to define proxy settings in the osmdata package itself. I'll see what responses you'll get. :)

**Comment by beingalink** [comment]
OK, I'm sorry. Seems like I was wrong. Setting environment variables as described [here](https://support.rstudio.com/hc/en-us/articles/200488488-Configuring-R-to-Use-an-HTTP-or-HTTPS-Proxy) didn't work, but reading the [issue](https://github.com/jeroen/curl/issues/1) you linked gave me the idea to define the environment variables for the proxy like this:
```
http_proxy = "user:pwd@proxy:port"
https_proxy = "user:pwd@proxy:port"
```
Now the proxy seems to get picked up just fine. So no need for the solution I posted above. Sorry for the hassle.

**Comment by mpadge** [comment]
Great that this discussion remains here for the record, i'd say. Thanks for solving this yourself!

**Comment by mpadge** [comment]
@beingalink there's now a useful answer on the [rOpenSci question](https://discuss.ropensci.org/t/windows-proxy-settings/990/2)

**Comment by prise6** [comment]
FYI, i had similar issue. In detail : `curl::has_internet()` returns always `FALSE` for some odd reason (see [nslookup](https://github.com/jeroen/curl/blob/b86dd07f6de764d30a69463f6d405221d438499e/src/nslookup.c) ) 
And solution : 
* `httr::use_proxy` / `httr::set_config` -> doesn't work 
* `.Renviron` (set http_proxy var) -> doesn't work

So i did something awful, but could be useful for someone:
I override the `has_internet()` function inside package `curl`.

````r
library(osmdata)
environmentIsLocked(asNamespace("curl"))
unlockBinding(sym = "has_internet", asNamespace("curl"))
assign(x = "has_internet", value = {function() T}, envir = asNamespace("curl"))
curl:::has_internet()
```

:disappointed: 

Works fine at the end.

**Comment by mpadge** [comment]
Interesting! Thanks for sharing that - hopefully won't be necessary for many, but great info for those in that dire predicament.
