### ISSUE TITLE
Querying the status of a custom Overpass API server

### ISSUE THREAD

**Issue by fzenoni** [ropensci/osmdata#112]
I am trying to use a custom Overpass API server. It is still a work in progress task, so I can't exclude that the problem actually resides on our side.

One of the problems I experience occurs when I query the status of the server with `osmdata`.

```r
library(osmdata)
set_overpass_url('http://13.95.169.24/api/interpreter')
x <- overpass_status()
x
$available
[1] FALSE

$next_slot
NULL

$msg
NULL
```

However it seems to me that according to the source code, `overpass_status()` is not querying the right URL. In fact, it should make a `httr::GET()` operation on 'http://13.95.169.24/api/status' or  'http://13.95.169.24/api/timestamp' (both give a status of 200 when queried manually), as it does when specific strings are found in the URL. Is my understanding correct?

**Comment by mpadge** [comment]
Thanks Florian, I'll check it out for you asap and report back.

**Comment by mpadge** [comment]
That commit should open up the possibility of using a custom overpass server. `overpass_status` will not necessarily return meaningful values for `$next_slot` and `$msg`, but should at least return `$available = TRUE`, and will thus enable queries to be passed to the server. This is a really important use-case, so please re-open issue if any further problems arise (and maybe rename it generic "custom overpass API server"). Nice work!

**Comment by fzenoni** [comment]
I am extremely grateful for you very prompt solution.
At a first glance everything seems to be functioning (I am using yet another different IP address compared to what I posted above, so I'm not sure what will happen if you try that specific one yourself).
I will update the name of the issue accordingly.

Thanks a lot!
