### ISSUE TITLE
Negation not working in add_osm_feature()

### ISSUE THREAD

**Issue by yaakovfeldman** [ropensci/osmdata#113]
I am trying to find all lines that have the `railway` key set to a value other than `rail`.

Using:

    > overpass.query <- opq(c(-1,50,1,54)) %>%
    +     add_osm_feature(key = "railway", value = "rail", key_exact = TRUE) %>%
    +     osmdata_sf()
    > overpass.query
    Object of class 'osmdata' with:
                 $bbox : 50,-1,54,1
        $overpass_call : The call submitted to the overpass API
            $timestamp : [ Tue 3 Dec 2017 12:28:34 ]
           $osm_points : 'sf' Simple Features Collection with 154337 points
            $osm_lines : 'sf' Simple Features Collection with 21797 linestrings
         $osm_polygons : 'sf' Simple Features Collection with 0 polygons
       $osm_multilines : 'sf' Simple Features Collection with 4 multilinestrings
    $osm_multipolygons : 'sf' Simple Features Collection with 0 multipolygons

I get all lines (and points, etc.) that ARE rail. But using `value="!rail"` always returns an empty geometry, regardless of how I set `key_exact` or `value_exact`.

Specifying a different value from the list at http://wiki.openstreetmap.org/wiki/Railways such as `funicular` works.

**Comment by mpadge** [comment]
I suspect it's just that you're using an older version of `osmdata`. Newer versions issue more extensive error messages, so when I run the above with `value = "!rail"`, I get
```
# runtime error: Query ran out of memory in "query" at line 4.
# It would need at least 517 MB of RAM to continue
```
The actual query returns a normal `http` status (200), so these were previously ignored, resulting in an empty object. It should now issue an error. Trying a smaller `bbox` should give what you want - but `value = "!rail"` is asking for a heap of stuff, so the `bbox` has to be pretty small. This query:
```
opq(c(-1,50.9,-0.9,51)) %>%
     add_osm_feature(key = "railway", value = "!rail") %>%
     osmdata_sf()
```
returns 150,000 points. You'll probably have to use more specific `key-value` pairs if you really want your query to cover such a large `bbox`. Appending successive `add_osm_feature()` calls is a logical **AND** operation, so you an easily refine queries with
```
opq(c(-1,50.9,-0.9,51)) %>%
     add_osm_feature(key = "railway", value = "!rail") %>%
     add_osm_feature(key = "railway", value = "!funicular") %>%
     add_osm_feature(key = "railway", value = "!...") %>%
     osmdata_sf()
```
Feel free to re-open issue if this hasn't solved your probs. Thanks for the feedback!

**Comment by yaakovfeldman** [comment]
Thank you
