### ISSUE TITLE
Broken example 4.2 in vignettes/osmdata.Rmd

### ISSUE THREAD

**Issue by gregor-d** [ropensci/osmdata#115]
Example in section "4.2 Relation example" (line 821) returns an empty object
https://github.com/ropensci/osmdata/edit/master/vignettes/osmdata.Rmd#L820

```
lcnr9 <- opq ('greater london uk') %>%
    add_osm_feature (key = "name", value = "London.Cycle.Network.Route.9",
                 value_exact = FALSE) %>%
    osmdata_sp()
sp::plot(lcnr9$osm_lines)
lcnr9
```
Object of class 'osmdata' with:
                 $bbox : 51.2867602,-0.5103751,51.6918741,0.3340155
        $overpass_call : The call submitted to the overpass API
            $timestamp : [ Fri 6 Dec 2017 18:34:19 ]
           $osm_points : 'sp' SpatialPointsDataFrame with 0 points
            $osm_lines : 'sp' SpatialLinesDataFrame with 0 lines
         $osm_polygons : 'sp' SpatialPolygonsDataFrame with 0 polygons
       $osm_multilines : 'sp' SpatialNADataFrame with 0 multilines
    $osm_multipolygons : 'sp' SpatialPolygonsDataFrame with 0 multipolygons

**Comment by mpadge** [comment]
yeah, you're right @gregor-d - thanks for picking that up. Something must have changed with the dataset. We'll have to replace that with a working example. cc @Robinlovelace

**Comment by Robinlovelace** [comment]
Aye will take a look.
