### ISSUE TITLE
getbb fails with unhelpful error message for Bristol, Connecticut

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/osmdata#117]
``` r
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.2, proj.4 4.9.2
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright
packageVersion("osmdata")
#> [1] '0.0.5.100'
r = getbb("Bristol", format_out = "sf_polygon")
plot(r)
```

![](https://i.imgur.com/iN7JqQB.png)

``` r
getbb("Bristol connecticut", format_out = "sf_polygon")
#> Error in apply(mat, 2, range): dim(X) must have a positive length
```

**Comment by Robinlovelace** [comment]
I think it should kick out an `sf` object representing the rectangular bb.

**Comment by mpadge** [comment]
Yeah, absolutely. I'll get into it asap. Thanks

**Comment by Robinlovelace** [comment]
I should be able to do that - kinda my area of the code-base. Let me know.

**Comment by Robinlovelace** [comment]
Job done. Actually in the OP it wasn't a rectangular bb that was killing it: it was that there was only 1 result. I also fixed it so it can provide rectangular polygonal outputs, e.g. for Accra (now in the dox in the PR).
