### ISSUE TITLE
Make all reference args const

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#125]
Following the sensible advice of the [google C++ style guide](https://google.github.io/styleguide/cppguide.html#Reference_Arguments), make all arguments passed by reference `const`, which means making all (current) variable args pointers instead of reference objects.

**Comment by virgesmith** [comment]
DON'T!!! You need to bear in mind their guidelines are more about living with a large legacy codebase. 

https://www.linkedin.com/pulse/20140503193653-3046051-why-google-style-guide-for-c-is-a-deal-breaker/

The mutable-ref-as-pointer is a particular insanity. Also "we don;t use exceptions" gives the game away: they mean "we have loads of legacy code that isnt exception-safe". Far more useful would be to read up on RAII: https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization and write modern C++.

**Comment by virgesmith** [comment]
Reckon this is a far better guide: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md

**Comment by mpadge** [comment]
thanks Andrew! I just needed to hear a well-informed "DON'T" on the matter. The don't use exceptions does indeed stick out as pretty bloody stupid, but even they admit that it wouldn't likely be that way if they were to start from scratch.
