### ISSUE TITLE
"General overpass server error" on example query

### ISSUE THREAD

**Issue by legengliu** [ropensci/osmdata#126]
Hi, please correct me if I'm missing an obvious solution to this, but I tried running the example query in the README:
```
q0 <- opq(bbox = c(-0.27, 51.47, -0.20, 51.50)) # Chiswick Eyot in London, U.K.
q1 <- add_osm_feature(q0, key = 'name', value = "Thames", value_exact = FALSE)
x <- osmdata_sf(q1)
```
And got this error:
```
Error in check_for_error(doc) : General overpass server error; returned:
OSM3S ResponseThe data included in this document is from www.openstreetmap.org. The data is made available under ODbL.Error: line 8: parse error: ';' expected - ')' found. Error: line 11: parse error: 
Unexpected end of input. Error: line 8: static error: Element "print" cannot be subelement of element "union".
```

I have tried other queries as well, and am getting the same error message when calling `osmdata_sf`, `osmdata_sp`, or `osmdata_xml`. I am confused because the exact same queries had worked for me a week ago. Is this an issue with the Overpass API itself?

**Comment by mpadge** [comment]
Oh yeah, I get the same. I'll find out what's going on and get back to you

**Comment by mpadge** [comment]
Thanks @legengliu for digging this one up. That commit should fix.

**Comment by PaoloFrac** [comment]
Hi @mpadge! I have some code that used to work about a month ago and I now get the same error highlighted above. I am combining a few **osmdata_sf** calls with **c()**. However none of them seems to run. Would you know how to fix it? Many thanks!

**Comment by mpadge** [comment]
Sorry @PaoloFrac can't really help with this error - the `overpass` server just gets overloaded these days it seems. The kinds of errors given above just indicate a server-side failure that I can't do anything about. :disappointed:

**Comment by PaoloFrac** [comment]
Thanks for your reply @mpadge. Do you think it is just a traffic problem or they actually change something on their side?

**Comment by mpadge** [comment]
I dunno. I suspect they do some pretty clever queuing that might end up with some heavy-usage IP addresses becoming rate-restricted.

**Comment by JimShady** [comment]
I thought that changing the overpass API (with the set_overpass_api() command) that is used would help with this error. I wrote a short piece of code to randomly choose which API to use so that I don't hammer them too much. Unfortunately it didn't really help. Well, kind of. The bottom one, kumi, seems to work for me still. The other three don't.

```
api_list <- c('http://overpass-api.de/api/interpreter',
              'https://lz4.overpass-api.de/api/interpreter',
              'https://z.overpass-api.de/api/interpreter',
              'https://overpass.kumi.systems/api/interpreter')

api_to_use <- sample(1:length(api_list), 1)

set_overpass_url(api_list[api_to_use]) 
```

**Comment by PaoloFrac** [comment]
Thanks for this. I will give it a try, and let's really hope they sort things out!

**Comment by mpadge** [comment]
@legengliu @PaoloFrac  this problem is now clearly pervasive - see #130 and same issue on [`osmplotr`](https://github.com/ropensci/osmplotr/issues/39). I'm going to have to try to find an effective work-around, and will report back when I do.

**Comment by mpadge** [comment]
sorry about this all who've suffered this complete loss of functionality:

1. It was all entirely my fault;
2. It was fixed a while ago in the current `dev` version; but
3. It was something so minor that I didn't realise it was going to have such pervasive effects

For now, you can just `devtools::install_github("ropensci/osmdata")` and all should be good. I'll get the fix on to CRAN asap. Thanks to all for pointing this out!

**Comment by JimShady** [comment]
^ What he said.

**Comment by lbuk** [comment]
The osmar package is affected as well. osmdata wasn't working until I installed it via github. 

Here's the osmar error message:
Space required after the Public Identifier
SystemLiteral " or ' expected
SYSTEM or PUBLIC, the URI is missing
Opening and ending tag mismatch: hr line 7 and body
Opening and ending tag mismatch: body line 4 and html
Premature end of data in tag html line 2
Error: 1: Space required after the Public Identifier
2: SystemLiteral " or ' expected
3: SYSTEM or PUBLIC, the URI is missing
4: Opening and ending tag mismatch: hr line 7 and body
5: Opening and ending tag mismatch: body line 4 and html
6: Premature end of data in tag html line 2
