### ISSUE TITLE
Remove cleanup.h and .cpp

### ISSUE THREAD

**Issue by virgesmith** [ropensci/osmdata#127]
The code can be safely deleted as it isn't used (and can't be used anyway - the template implementations are in a source file, and are explicitly disabled for double, osmid_t and std::string  (by unimplemented specialisation))

just calling vec.clear() on the outermost vector will suffice. And bear in mind clear does not free any memory - the vector is emptied but its capacity is unchanged. If you really want to free up memory you should clear() then shrink_to_fit()

**Comment by mpadge** [comment]
Thanks @virgesmith - shall do!
