### ISSUE TITLE
General overpass server error

### ISSUE THREAD

**Issue by mtennekes** [ropensci/osmdata#128]
When I run the examples from `osmdata_sf` I get an error message:

```{r}
hampi_sf <- opq ("hampi india") %>%
  add_osm_feature (key="historic", value="ruins") %>%
  osmdata_sf()
```

Error in check_for_error(doc) : General overpass server error; returned:
OSM3S ResponseThe data included in this document is from www.openstreetmap.org. The data is made available under ODbL.Error: line 8: parse error: ';' expected - ')' found. Error: line 11: parse error: Unexpected end of input. Error: line 8: static error: Element "print" cannot be subelement of element "union". 

I tested it under Ubuntu and W10.

**Comment by JimShady** [comment]
Same error on Windows 10.

**Comment by mpadge** [comment]
The bad news here is that this is the same as [this issue](https://github.com/ropensci/osmdata/issues/126), and is, as reflected in the error text, a "General overpass server error". Unfortunately, all you can do is keep trying. It gives "Unexpected end of input" because there is no input - overpass silently fails and returns nothing.

**Comment by mpadge** [comment]
@mtennekes @JimShady this problem is now clearly pervasive - see #130 and same issue on [`osmplotr`](https://github.com/ropensci/osmplotr/issues/39). I'm going to have to try to find an effective work-around, and will report back when I do.

**Comment by mpadge** [comment]
(copy of same in #126) sorry about this all who've suffered this complete loss of functionality:

1. It was all entirely my fault;
2. It was fixed a while ago in the current `dev` version; but
3. It was something so minor that I didn't realise it was going to have such pervasive effects

For now, you can just `devtools::install_github("ropensci/osmdata")` and all should be good. I'll get the fix on to CRAN asap. Thanks to all for pointing this out!
