### ISSUE TITLE
Error: package or namespace load failed

### ISSUE THREAD

**Issue by lbuk** [ropensci/osmdata#133]
I'm getting this error after loading the package: 

Error: package or namespace load failed for ‘osmdata’ in get(Info[i, 1], envir = env):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/sp/R/sp.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

Would it be possible to check this?

**Comment by mpadge** [comment]
likely an out-of-date version of `sp`. try
```
update.packages (ask = FALSE)
```
and see if that fixes
