### ISSUE TITLE
Use httr retry

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#134]
Instead of current explicit retry code

**Comment by maelle** [comment]
I wonder if `crul` has an equivalent for that by the way (in case you ever want to switch :wink: ) 🤔 cc @sckott

**Comment by sckott** [comment]
No, it doesn't have retry.  but i've opened an issue to think about it https://github.com/ropensci/crul/issues/89

**Comment by sckott** [comment]
okay, we have a retry method now https://github.com/ropensci/crul/pull/95 - see docs for `?HttpClient`
