### ISSUE TITLE
Website not up-to-date

### ISSUE THREAD

**Issue by maelle** [ropensci/osmdata#135]
Just noticed this because the trimming function is documented in the vignette but not in the website.

For auto-deploying the `pkgdown` website, you might be interested in https://github.com/ropenscilabs/tic by @krlmr &co. I'm happy to experiment with that in this repo if you trust me. :wink:

**Comment by mpadge** [comment]
Thanks @maelle, and absolutely yes please, feel free to update anything you find like this if you've got the time and inclination to do so.

I haven't `tic`'ed the website coz there are still a few things that don't work so well with that, such as different `devtools` versions triggering warnings and therefore leading to travis failures. But if you can find a way around this, then by all means, please do so! That would be fabulous!

**Comment by maelle** [comment]
Will look into it later this month or in September!

What kind of warnings did you get? I guess I'll see it for myself though. :joy:

**Comment by mpadge** [comment]
Warnings are now issued by latest devtools  if `R CMD check` is run on system with earlier devtools (ie, travis). I don't understand why these have been made  warnings and not simple messages, but warnings they are, and so travis fails
