### ISSUE TITLE
Alternative overpass APIs

### ISSUE THREAD

**Issue by JimShady** [ropensci/osmdata#140]
Hi Mark,

When I use osmadata I often put this inside my loop to download the data I need so that I don't burden any of the APIs too much.

```
api_list <- c('http://overpass-api.de/api/interpreter',
              'https://lz4.overpass-api.de/api/interpreter',
              'https://z.overpass-api.de/api/interpreter',
              'https://overpass.kumi.systems/api/interpreter')

api_to_use <- sample(1:length(api_list), 1)

set_overpass_url(api_list[api_to_use]) 

rm(api_to_use, api_list)
```

If this is something that you think appropriate to include in the main osmdata package, and you could point me in the right direction, I'd be happy to try and do so with an edit and pull request (I've not contributed to a project using github before and I'm keen to try).

Cheers, James.

**Comment by mpadge** [comment]
Sorry James, just re-saw this issue that I'd somehow overlooked of late. Now that I've got `dodgr` up to a much more acceptable state, it's time for all these issues. This one actually seems like a good idea. The code for initially setting the API URL is [here](https://github.com/ropensci/osmdata/blob/master/R/zzz.R) in the first `.onLoad` function. You'd just need to change that to `sample` one of the official addresses. A PR would be very welcome, please!

**Comment by mpadge** [comment]
Closed with [this PR](https://github.com/ropensci/osmdata/pull/149)
