### ISSUE TITLE
osmdata_sc verbs

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#151]
Extending from #148, the `osmdata_sc()` function could and should incorporate an additional parameter, `sc_verb = "SC"` with the following options (case-insensitive):
1. `"SC"`
2. `"SC0"`
3. `"path"`
4. `"vertex"`
5. `"coord"`
6. Verb for `dodgr_contract_graph` which reduces objects to junction points only by removing all redundant edges
7. (Future stuff?) Verb for converting result of 6 into fundamental cycles to allow conversion to mesh

Note re: 6 that the term "graph" is only `dodgr`-specific, but the verb should be general and not presume that the input objects can be or are represented in graph form.

@mdsumner Input here much appreciated, please!

**Comment by mpadge** [comment]
Yeah, it all comes from the bunbled [`rapidxmi.h`](https://github.com/ropensci/osmdata/blob/master/src/rapidxml.h), which reads everything and just returns pointers to all the bits. So it's just iterating over pointers. The initial reading is lightning fast, but somewhere in the subsequent iteration it really slows down, so i do have to examine that a bit deeper

**Comment by mpadge** [comment]
Now time to return to this. Yes, you're understanding above is correct - the `osmdata_sc()` call currently downloads and reads all-as-one, and so returns the single, currently [`SC.default`](https://github.com/hypertidy/silicate/blob/master/R/SC-model.R#L32) (not `SC0.default`), because this happens to be a comprehensively inclusive representation of all original data in an OSM doc. My idea was that subsequent conversion (to `SC0`, `PATH`, whatever) could then be handled via `silicate`.

This is turn reflects the abiding vision of `osmdata` as a package that does the best job it can of returning all data in a way that best represents the original / underlying OSM structure (hence the need for the vignette on [`sf` translation](https://ropensci.github.io/osmdata/articles/osm-sf-translation.html).) So the core mechanisms of `osmdata` have always been envisioned such that only one return object of whatever desired form will ever need to be extracted from a single `overpass` call.

The idea of downloading some kind of master `SC` object - or more likely, the raw `xml` (or `pbf` even?) - and then running multiple extractions depending on user needs thus kinda runs counter to this vision. This vision may indeed be better off modified in some way, but I still think it would place less of a burden on users - and likely of no small importance, would also ease adoption of `silicate` - if the initial usage follows this simple pattern. "Give me some OSM data in silicate format", rather than forcing users to first answer the non-trivial question, "Hmmm, what kind of silicate format do I actually want?" ... 

I guess in technical terms what I am presuming is that conversion from `SC.default` to other `silicate` forms would be no slower handled through primary `silicate` operations than hard-coding it at this end, and that doing so would place a considerably lower burden on use. Thoughts much appreciated here

**Comment by mdsumner** [comment]
Oh that's great, I'm so used to converting other types I wasn't even thinking of this in that way. That's very much answered my qs!

**Comment by mpadge** [comment]
Closing to revert to implementation of single "master" [`osmdata_sc()` function](https://github.com/ropensci/osmdata/issues/148). Other [`SC`](https://github.com/hypertidy/silicate) verbs can simply be applied to that.
