### ISSUE TITLE
trim_osmdata with regular bbox/sp/sf class

### ISSUE THREAD

**Issue by michielvandijk** [ropensci/osmdata#153]
Hi,
 I would like to trim the polygons I obtain from my osm query to country/regional borders. However, the trim_osmdata function only seems to accept a matrix that is produced with the getbb function, which produces "a matrix presenting a bounding polygon". I understand what this is but I am not used to work with this type of class (and I guess this also holds for others). Would it be possible to add the possibility to use an sp or sf class (e.g. a SpatialPolygonsDataFrame, which is normally used for mapping countries) inside trim_osmdata? Or alternatively, if there is such a function, how do I produce a "bounding polygon" using a standard sp or sf class?

Many thanks!
Michiel

**Comment by mpadge** [comment]
That's a great idea Michiel, and should be pretty easy to add. You'll see here when I've done it, and I'll put some illustrative code in. I'll add this issue to [release schedule](https://github.com/ropensci/osmdata/projects/1) right now. In the meantime, if you've got an `sf` object, you can just use `st_coordinates()` to get the required matrix form, or `coordinates(spobj)` for `sp` to get a matrix.

**Comment by michielvandijk** [comment]
Thanks! The st_coordinates works fine.
