### ISSUE TITLE
Add function to aggregate all POI from osmdata object as table of points

### ISSUE THREAD

**Issue by fzenoni** [ropensci/osmdata#156]
When querying POI from OSM, most of the time they don't come in a single shape. Querying bus stops, for instance could lead at obtaining points as well as polygons (describing e.g. the shape of a platform).

This is rather annoying whenever one needs to make a simple plot of the collected information, or gather some consistent statistics, especially because of the high variety of the crowd-sourced information in OSM.
Therefore, some time ago I wrote a function that takes an osmdata object and returns a sf-extended data.frame including only points, by replacing the line or polygon description with their centroid.

The function in question is basically this one: https://github.com/fzenoni/SotM-poster-submission/blob/master/R-scripts/aggregate_points.R

```r
library(sf)
library(osmdata)
q <- getbb ("portsmouth", display_name_contains = "USA") %>%
    opq () %>% 
    add_osm_feature("amenity", "restaurant")  %>% osmdata_sf() %>% unique_osmdata()
```
By printing `q` one obtains:
```
Object of class 'osmdata' with:
                 $bbox : 43.0135509,-70.8229994,43.0996118,-70.7279298
        $overpass_call : The call submitted to the overpass API
            $timestamp : [ Tue 3 Nov 2018 14:48:56 ]
           $osm_points : 'sf' Simple Features Collection with 40 points
            $osm_lines : 'sf' Simple Features Collection with 0 linestrings
         $osm_polygons : 'sf' Simple Features Collection with 24 polygons
       $osm_multilines : 'sf' Simple Features Collection with 0 multilinestrings
    $osm_multipolygons : 'sf' Simple Features Collection with 0 multipolygons
```
Then applying:
```r
aggregate_points(q)
```
one obtains
```r
Simple feature collection with 64 features and 43 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: -70.80734 ymin: 43.01347 xmax: -70.73388 ymax: 43.0987
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
First 10 features:
       osm_id                    name addr.city addr.housenumber addr.postcode addr.state addr.street    amenity  cuisine delivery email
1  1123325984 Badger Island Pizzaeria      <NA>             <NA>          <NA>       <NA>        <NA> restaurant     <NA>     <NA>  <NA>
2  1389429747    Cataqua Public House      <NA>             <NA>          <NA>       <NA>        <NA> restaurant american     <NA>  <NA>
3  1848960997              Fresh City      <NA>             <NA>          <NA>       <NA>        <NA> restaurant     <NA>     <NA>  <NA>
4  2395563084                Chipotle      <NA>             <NA>          <NA>       <NA>        <NA> restaurant  mexican     <NA>  <NA>
5  4382020138            Cafe Nostimo      <NA>               72          <NA>       <NA> Mirona Road restaurant    greek     <NA>  <NA>
6  4404952260                 Kim Lai      <NA>             <NA>          <NA>       <NA>        <NA> restaurant  chinese     <NA>  <NA>
7  4418911394                    Cava      <NA>             <NA>          <NA>       <NA>        <NA> restaurant     <NA>     <NA>  <NA>
8  4418925793           Lexie's Joint      <NA>             <NA>          <NA>       <NA>        <NA> restaurant     <NA>     <NA>  <NA>
9  4418925794         Wellington Room      <NA>             <NA>          <NA>       <NA>        <NA> restaurant     <NA>     <NA>  <NA>
10 4418926995                  Row 34      <NA>             <NA>          <NA>       <NA>        <NA> restaurant     <NA>     <NA>  <NA>
    fax internet_access internet_access.fee level microbrewery         name.en opening_hours outdoor_seating payment.bitcoin
1  <NA>            <NA>                <NA>  <NA>         <NA>            <NA>          <NA>            <NA>            <NA>
2  <NA>            <NA>                <NA>  <NA>          yes            <NA>          <NA>            <NA>            <NA>
3  <NA>            <NA>                <NA>  <NA>         <NA>            <NA>          <NA>            <NA>            <NA>
4  <NA>            <NA>                <NA>  <NA>         <NA>            <NA>          <NA>            <NA>            <NA>
5  <NA>            <NA>                <NA>  <NA>         <NA>            <NA>          <NA>             yes            <NA>
6  <NA>            <NA>                <NA>  <NA>         <NA>            <NA>          <NA>            <NA>            <NA>
7  <NA>            <NA>                <NA>  <NA>         <NA>            Cava          <NA>            <NA>            <NA>
8  <NA>            <NA>                <NA>  <NA>         <NA>   Lexie's Joint          <NA>            <NA>            <NA>
9  <NA>            <NA>                <NA>  <NA>         <NA> Wellington Room          <NA>            <NA>            <NA>
10 <NA>            <NA>                <NA>  <NA>         <NA>          Row 34          <NA>            <NA>            <NA>
   payment.cryptocurrencies payment.dash           phone shop short_name smoking takeaway toilets toilets.access                website
1                      <NA>         <NA>            <NA> <NA>       <NA>    <NA>     <NA>    <NA>           <NA>                   <NA>
2                      <NA>         <NA>            <NA> <NA>       <NA>    <NA>     <NA>    <NA>           <NA>                   <NA>
3                      <NA>         <NA>            <NA> <NA>       <NA>    <NA>     <NA>    <NA>           <NA>                   <NA>
4                      <NA>         <NA>            <NA> <NA>       <NA>    <NA>     <NA>    <NA>           <NA>                   <NA>
5                      <NA>         <NA> +1-603-436-3100 <NA>       <NA>    <NA>      yes    <NA>           <NA> http://cafenostimo.com
6                      <NA>         <NA>            <NA> <NA>       <NA>    <NA>      yes    <NA>           <NA>                   <NA>
7                      <NA>         <NA>            <NA> <NA>       <NA>    <NA>     <NA>    <NA>           <NA>                   <NA>
8                      <NA>         <NA>            <NA> <NA>       <NA>    <NA>     <NA>    <NA>           <NA>                   <NA>
9                      <NA>         <NA>            <NA> <NA>       <NA>    <NA>     <NA>    <NA>           <NA>                   <NA>
10                     <NA>         <NA>            <NA> <NA>       <NA>    <NA>     <NA>    <NA>           <NA>                   <NA>
   addr.country alt_name brand brand.wikidata building building.levels building_level contact.phone contact.website craft drive_through note
1          <NA>     <NA>  <NA>           <NA>     <NA>            <NA>           <NA>          <NA>            <NA>  <NA>          <NA> <NA>
2          <NA>     <NA>  <NA>           <NA>     <NA>            <NA>           <NA>          <NA>            <NA>  <NA>          <NA> <NA>
3          <NA>     <NA>  <NA>           <NA>     <NA>            <NA>           <NA>          <NA>            <NA>  <NA>          <NA> <NA>
4          <NA>     <NA>  <NA>           <NA>     <NA>            <NA>           <NA>          <NA>            <NA>  <NA>          <NA> <NA>
5          <NA>     <NA>  <NA>           <NA>     <NA>            <NA>           <NA>          <NA>            <NA>  <NA>          <NA> <NA>
6          <NA>     <NA>  <NA>           <NA>     <NA>            <NA>           <NA>          <NA>            <NA>  <NA>          <NA> <NA>
7          <NA>     <NA>  <NA>           <NA>     <NA>            <NA>           <NA>          <NA>            <NA>  <NA>          <NA> <NA>
8          <NA>     <NA>  <NA>           <NA>     <NA>            <NA>           <NA>          <NA>            <NA>  <NA>          <NA> <NA>
9          <NA>     <NA>  <NA>           <NA>     <NA>            <NA>           <NA>          <NA>            <NA>  <NA>          <NA> <NA>
10         <NA>     <NA>  <NA>           <NA>     <NA>            <NA>           <NA>          <NA>            <NA>  <NA>          <NA> <NA>
   operator                   geometry
1      <NA>   POINT (-70.7513 43.0823)
2      <NA> POINT (-70.80446 43.08788)
3      <NA> POINT (-70.79982 43.09435)
4      <NA> POINT (-70.80061 43.09415)
5      <NA> POINT (-70.77495 43.04808)
6      <NA> POINT (-70.76912 43.05516)
7      <NA> POINT (-70.75703 43.07768)
8      <NA>  POINT (-70.76452 43.0738)
9      <NA> POINT (-70.75647 43.07888)
10     <NA> POINT (-70.76055 43.07738)
```

I wrote the function with care, but I never saw my code "in production", so it could certainly be improved.

Would such a function be interesting for the `osmdata` package?

**Comment by mpadge** [comment]
Intriguing idea. Maybe an `osmdata_filter(x, osm_id = NULL)` function that filters the `osmdata` object to contain only those elements that are part of the object with `osm_id`? (I think `_aggregate` is a bit deceptive, because the underlying procedure is more like disaggregation, but that word is likely too confusing, ergo my suggestion of `_filter()` - but open to other suggestions.) Matching `osm_id` columns is pretty straightforward, so this should work without even having to specify what kind of object the argument refers to.

Questions immediately arise, however, such as:

What if `osm_id` refers to an item of `osm_points` - much like what you've implemented in your excellent code - and we actually want all objects which contain that point? That's a fundamentally different procedure from specifying, say, an `osm_polygons` object and filtering all lines and points that are part of that polygon. We end up with a notion of "filter up" and "filter down", akin to what [`osmar`](https://cran.r-project.org/package=osmar) originally implemented. Thoughts? @Robinlovelace?

```
osmdata_filter <- function (x, osm_id = NULL, direction = "down") {
    if (is.null (osm_id)) stop("need an ID")
    direction <- match.arg (c ("up", "down", "both"))
   ...
}
```

**Comment by mpadge** [comment]
And hey @fzenoni - [great poster](https://github.com/fzenoni/SotM-poster-submission)! Did you know about our [`dodgr` package](https://github.com/ATFutures/dodgr)? It is designed to interface directly with `osmdata` to give travel distances, times, whatever. I'm biased, coz I developed it, but I think it's a bit more straightforward to use than OSMR - and also more powerful.

**Comment by fzenoni** [comment]
Thank you for your kind words!

I confess I am already a bit lost. When you say:
> Maybe an `osmdata_filter(x, osm_id = NULL)` function that filters the `osmdata` object to contain only those elements that are part of the object with `osm_id`?

do you mean that it would be a way to "reduce" an object (say, a polygon) to a single point? As an alternative to computing its centroid? Could you make a concrete example?

Concerning `dodgr` I read the vignette a while ago, but having already a sort of workflow with OSRM I just recycled that experience. Since you mentioned it am certainly going to try to implement something with it.

**Comment by mpadge** [comment]
Oh sorry, i now see that i misunderstood what you were doing - and now i see what the purpose of your code was. Um, yes, that is a really good idea, but alas in this case I'm afraid I'm going to have to say this is not a good idea for `osmdata` itself, because the package has the singular abiding aim of remaining as true as possible to the original data stored in OSM itself. The package has a self-imposed discipline of not modifying that representation other than as absolutely necessary (for example, to wrangle it into `sf` form).

That is in no way intended to imply that this is not a good idea - it really is! It's just that the package itself is not the place for a function like that. Your envisioned application is really more a plotting or visualisation-centred thing, right? Maybe an appropriate place for such a function might be something like [`osmplotr`](https://github.com/ropensci/osmplotr)? On the other hand, that package is likely to be heavily revised sometime soon-ish (when I find time), and will be done in conjunction with the issue of developing default [plot methods for `osmdata`](https://github.com/ropensci/osmdata/issues/77). In short: All very unknown territory at present. Feel free to suggest any alternative place you see such a function fitting. @Robinlovelace [`stplanr`](https://github.com/ropensci/stplanr) perhaps?

**Comment by fzenoni** [comment]
OK, this is the sort of answer I was looking for. It's perfectly fine, I understand your motivations. Indeed the main goal is to simplify my own visualization workflow.

My horizon is limited so I don't know any alternatives. Thanks a lot for your time and positive remarks!
