### ISSUE TITLE
Rewrite `rapidml` from scratch

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#158]
I now know a lot more than when this package started, and can see the [`rapidml` header](https://github.com/ropensci/osmdata/blob/master/src/rapidxml.h) could fairly easily be re-written from scratch as a custom OSM `XML` parser that would do the storage during initial reading. Interestingly, and excitingly for @mdsumner's [`silicate`](https://github.com/hypertidy/silicate) work, this direct store-on-read procedure is only really possible with and because of [`silicate`](https://github.com/hypertidy/silicate). The entire OSM structure is in essence fully `silicate`-compliant, and can be directly stored line-for-line as read.

This *should* ultimately enable the entire package to be re-written to simply dump directly to `SC` format, and then use `silicate` to convert outputs to other formats. (Plus some additional fiddling to insert the "hidden" but necessary row names containing OSM IDs.) MIke, I've done some preliminary comparisons of direct SC-storage, and for the test data set (a chunk of about 1/3 of Melbourne streets), the current 15-16s reduces to about 0.4s. So we're looking at least a tenfold boost in speed, which is well worth pursuing.

Related to general `osmdata_sc` issue #148.

**Comment by mdsumner** [comment]
wow ;)
