### ISSUE TITLE
`c.osmdata()` method and `NULL` values 

### ISSUE THREAD

**Issue by loreabad6** [ropensci/osmdata#162]
I am trying to use the `c` aggregation inside a function which requests features for different bounding areas. I have two main problems. 

First problem:
-------------

Sometimes the query returns no results, and when I try to use the `c` function I get an error, e.g.

```
osm_bb <- 'gouda, netherlands'

leisure_values <- c(
    'park','nature_reserve','playground'
  )
  
 leisure <- opq(bbox = osm_bb) %>%
    add_osm_feature(key ='leisure', value = leisure_values, value_exact = T) %>%
    osmdata_sf()

leisure

Object of class 'osmdata' with:
                 $bbox : 51.996258,4.6594546,52.0401197,4.7573299
        $overpass_call : The call submitted to the overpass API
                 $meta : metadata including timestamp and version numbers
           $osm_points : 'sf' Simple Features Collection with 229 points
            $osm_lines : NULL
         $osm_polygons : 'sf' Simple Features Collection with 16 polygons
       $osm_multilines : NULL
    $osm_multipolygons : NULL

landuse <- opq(bbox = osm_bb) %>%
    add_osm_feature(key ='landuse', value ='retail', value_exact = T) %>%
    osmdata_sf() 

landuse

Object of class 'osmdata' with:
                 $bbox : 51.996258,4.6594546,52.0401197,4.7573299
        $overpass_call : The call submitted to the overpass API
                 $meta : metadata including timestamp and version numbers
           $osm_points : NULL
            $osm_lines : NULL
         $osm_polygons : NULL
       $osm_multilines : NULL
    $osm_multipolygons : NULL

c(leisure, landuse)
Error in c.osmdata(leisure, landuse) : 
  All objects must be either osmdata_sf or osmdata_sp
```

I understand the error comes from [this part of the code](https://github.com/ropensci/osmdata/blob/0cbb265c146b5d68b99487a0ad610ecc717f7586/R/osmdata-methods.R#L73-L78) as all of the `sf` objects are actually `NULL`.

I am now using a not so "beautifully coded" workaround that helps me deal with it:

```
null_landuse <- landuse %>% magrittr::extract(4:length(landuse)) %>% sapply(is.null)
  
if(null_landuse %>% all)
{
    c(leisure)
} else 
{
    c(leisure, landuse)
}

Object of class 'osmdata' with:
                 $bbox : 51.996258,4.6594546,52.0401197,4.7573299
        $overpass_call : The call submitted to the overpass API
                 $meta : metadata including timestamp and version numbers
           $osm_points : 'sf' Simple Features Collection with 229 points
            $osm_lines : NULL
         $osm_polygons : 'sf' Simple Features Collection with 16 polygons
       $osm_multilines : NULL
    $osm_multipolygons : NULL
```
But I am not completely convinced with it. Once I had this I ran into another problem:

Second problem:
---------------------------

When I try to use the `c` function when some *osm* data frames are `NULL` I get an error on [this part of the code](https://github.com/ropensci/osmdata/blob/0cbb265c146b5d68b99487a0ad610ecc717f7586/R/osmdata-methods.R#L112). Now here the problem is, as far as I understand the code, that when the first element in the `c` function is `NULL`, then the `nrow()` cannot be computed. I can better illustrate this with an example:

Considering the same *Gouda* bounding box, and the `leisure` object computed before.

```
public_transport <- opq(bbox = osm_bb) %>%
    add_osm_feature(key ='public_transport', value ='station', value_exact = T) %>%
    osmdata_sf()

public_transport

Object of class 'osmdata' with:
                 $bbox : 51.996258,4.6594546,52.0401197,4.7573299
        $overpass_call : The call submitted to the overpass API
                 $meta : metadata including timestamp and version numbers
           $osm_points : 'sf' Simple Features Collection with 1 points
            $osm_lines : NULL
         $osm_polygons : NULL
       $osm_multilines : NULL
    $osm_multipolygons : NULL
```

If I do: 

```
c(leisure,public_transport)

Object of class 'osmdata' with:
                 $bbox : 51.996258,4.6594546,52.0401197,4.7573299
        $overpass_call : The call submitted to the overpass API
                 $meta : metadata including timestamp and version numbers
           $osm_points : 'sf' Simple Features Collection with 230 points
            $osm_lines : NULL
         $osm_polygons : 'sf' Simple Features Collection with 16 polygons
       $osm_multilines : NULL
    $osm_multipolygons : NULL
```

It works great because `osm_polygons` for `leisure` is not `NULL`, but if I do:

```
c(public_transport,leisure)

Error in rep(NA, nrow(resi)) : invalid 'times' argument
```

Because the object is `NULL`.

The case here is that since I am working with this queries inside a function I cannot predict when these cases are going to happen. I am still thinking of a workaround, but probably going to the code would be more efficient!

**Comment by mpadge** [comment]
Oh yeah, another definite issue with our code. I'll fix that up asap. Thanks!

**Comment by Dris101** [comment]
I have found that creating a 'null' sf such as
`sfNull <- st_sf(geometry=st_sfc())`
and then doing (for example)
`public_transport$osm_lines <- sfNull`
_etc._ for all the NULL ones enables me to merge them successfully with `c.osmdata()`. This may not be the best way of doing it in the library code but might be a short term fix.

**Comment by mpadge** [comment]
That commit simply allows all but one object submitted to `c.osmdata` to be `NULL`, and returns silently from all of the above calls.
