### ISSUE TITLE
General overpass server error

### ISSUE THREAD

**Issue by MiKatt** [ropensci/osmdata#170]
I thought this issue was fixed but I still get the error when I run the code from the GitHub example:

> Error in check_for_error(doc) : General overpass server error; returned:
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL. runtime error: open64: 2 No such file or directory /home/roles/overpass/db/nodes.bin File_Blocks::File_Blocks::1 

`x <- opq(bbox = c(-0.27, 51.47, -0.20, 51.50)) %>% # Chiswick Eyot in London, U.K.
  add_osm_feature(key = 'name', value = "Thames", value_exact = FALSE) %>%
  osmdata_sf()
`
I have installed from GitHub, not CRAN; running on Linux Mint 19 Tara.

**Comment by mpadge** [comment]
That's an error delivered directly from the overpass server, not from `osmdata`. It usually means either that the servers are over-burdened, in which case simply waiting a few minutes should work, or your IP address has been identified as having recently placed too high a burden on the servers, in which case the wait for a client reset may be a bit longer (like a day or so).
