### ISSUE TITLE
trim_osmdata not trimming osm_polygons

### ISSUE THREAD

**Issue by alanlzl** [ropensci/osmdata#171]
When $osm_lines is NULL, the trim_osmdata() function will not trim osm_polygons.

Here's an example:
Object of class 'osmdata' with:
  $bbox : 47.629922,-122.436065,47.67193,-122.377663
  $overpass_call : The call submitted to the overpass API
  $meta : metadata including timestamp and version numbers
  $osm_points : 'sf' Simple Features Collection with 93604 points
  $osm_lines : NULL
  $osm_polygons : 'sf' Simple Features Collection with 9655 polygons
  $osm_multilines : NULL
  $osm_multipolygons : 'sf' Simple Features Collection with 14 multipolygons

I think it's caused by the if statement in code "./trim-osmdata.R" line 166 and line 193.

**Comment by mpadge** [comment]
Thanks, I'll have a look

**Comment by mpadge** [comment]
Yeah, you're definitely right with the cause being those lines - would you care to submit a pull request with a fix? You'd just need to replace `if $osm_lines` with `if $osmlines | $osm_polygons` and same for `multilines -> multilines | multipolygons.` That'd be great
