### ISSUE TITLE
Can't trim osm polygons

### ISSUE THREAD

**Issue by ccamara** [ropensci/osmdata#174]
When trying to reproduce the code [in your example](https://ropensci.github.io/osmdata/articles/osmdata.html#bounding-boxes-the-getbb-function) to try to trim osmdata within a polygon, I get the following error:

```r
bb <- getbb ('london uk', format_out = 'polygon')
x <- opq(bbox = bb) %>%
    add_osm_feature(key = 'highway', value = 'motorway') %>%
    osmdata_sf () %>%
    trim_osmdata (bb)
# Error in bbox_to_string(bbox) : bbox must be numeric
```

PS: I have just discovered this package and it is amazing. Kudos!

**Comment by mpadge** [comment]
Thanks, I just fixed that one in #171. If you install dev version from gh, it should work. Please confirm by closing issue :smile:

**Comment by ccamara** [comment]
Thanks for the reply and for solving it. Unfortunately, I am not confident with installing dev packages (don't have experience in R packages, though). Are there any plans to update CRAN version with this change anytime soon? If so, I would wait.

**Comment by mpadge** [comment]
Yeah, no worries, I'll push a new version to CRAN next week. In the meantime, it's as simple as
``` r
remotes::install_github("ropensci/osmdata")
```
That should work for you. Otherwise, I'll leave this issue open to remind myself to ping you here when new version appears.

**Comment by ccamara** [comment]
Thank you very much!

**Comment by mpadge** [comment]
New version 0.1.0 on CRAN now.

**Comment by ccamara** [comment]
Great!
