### ISSUE TITLE
Trim osmdata that extends beyond boundary

### ISSUE THREAD

**Issue by alanlzl** [ropensci/osmdata#175]
I see that trim_osmdata function has an "exclude" option. If there's an object laying over the boundary, we can either include it or exclude it. Is there any way where we can somehow **cut** the object and only keep the portion that's within the boundary?

I know implementation can be hard. Just some random ideas here:
- For a line:
   1) use sp::point.in.polygon to check which points of the _object_ is within the _boundary_.
   2) create a new line using points from 1)
- For a polygon:
  1) use sp::point.in.polygon to check which points of the _object_ is within the _boundary_.
  2) use sp::point.in.polygon to check which points of the _boundary_ is within the _object_.
  3) take union of 1) and 2) and create a new polygon. 

Here's an example: I'm trying to only keep the green portion of picture 1.

![BugImg_Sml](https://user-images.githubusercontent.com/15748113/56487857-70fa5400-6491-11e9-94a5-e254007d4129.PNG)

![BugImg_Lrg](https://user-images.githubusercontent.com/15748113/56487844-68a21900-6491-11e9-9e0e-ab3fe1760be3.PNG)

Thanks!

**Comment by mpadge** [comment]
This is a good idea, and one that has been raised before, but - the big *but* - the abiding ethos of the `osmdata` package is to deliver data that remain true to the underlying OSM data themselves. Cutting OSM ways or relations into pieces is geometrically very simple, but it would require re-labelling all components to avoid any presumption that these things are part of OSM. That then becomes very complex indeed, and violates the principle of the package.

We are nevertheless developing a bunch of tools to enable these kinds of operations, mostly around the [`silicate` format](https://github.com/hypertidy/silicate), already exported here via [`osmdata_sc()`](https://ropensci.github.io/osmdata/reference/osmdata_sc.html). The `SC::filter()` method will work straight away on those data, and they are also immediately compatible with, for example, [`mapdeck`](https://github.com/SymbolixAU/mapdeck), as demonstrated in the [new `osmdata` vignette](https://ropensci.github.io/osmdata/articles/osmdata-sc.html).
