### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#185]
like [`dodgr`](https://github.com/ATFutures/dodgr/issues/108), and inspired by [`stplanr`](https://github.com/ropensci/stplanr/issues/334)

**Comment by Robinlovelace** [comment]
Could ask my housemate Pete Hudspith if you'd like an illustrator's take on this: https://www.peterhudspith.com/

**Comment by Robinlovelace** [comment]
Awesome logo @mpadge !

**Comment by mpadge** [comment]
yeah, had to write my own bloody code to mask a map in hex shape to use as background image. it's been a very longstanding background task that one ... I should make my own "hex" package out of it, because it's mighty damn useful that! Especially noting that [`hexSticker`](https://github.com/GuangchuangYu/hexSticker) does not do masking, nor can `ggplot2`, so a png ends up opaquely filled to all rectangular edges. The `osmdata` logo is transparent in all pixels outside the hexagon. Your `stplanr` one is too -- and was the direct inspiration here -- but this code now does the entire process in R. Feel free to pifler / adapt / whatever ... [code here](https://github.com/ropensci/osmdata/blob/master/data-raw/hex-script.Rmd)
