### ISSUE TITLE
remove geometry names?

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#188]
As suggested by @edzer in [this `sf` issue](https://github.com/r-spatial/sf/issues/1177), the list names aren't strictly necessary, because the `osm_id` column always exists anyway, so that could be used instead. Only difference will be the `multi*` objects, for which geometry names also include the official OSM roles appended to the ID, but that should just require passing an additional two columns (id and role) along with the geometry. Seems worth doing to avoid issues like the above, and the associated [`leaflet` issue](https://github.com/rstudio/leaflet/issues/631), all of which are caused by these named list items.

**Comment by Robinlovelace** [comment]
I'd say definitely as it seems to be causing issues in ggplo2 also: https://stackoverflow.com/questions/59144491/r-unusual-error-plotting-multipolygons-with-ggplot-geom-sf-and-openstreetmap/59153204#59153204

**Comment by mpadge** [comment]
That commit adds new `unname_osmdata_sf` function which resolves all of these issues, yet which also warns that using this function removes ability to use the package and resultant data as intended.

**Comment by edzer** [comment]
The issues came up using osmdata-generated objects in dplyr, leaflet and (as @Robinlovelace reported above) in ggplot2. I don't see how users of osmdata are now going to learn where the problem comes from when they run into one of those issues, how they would find your `unname_osmdata_sf` function, and why they would not raise the issue at one of the other three packages. As you commented on Oct 22, why don't you put the labels somewhere else, following the `sf` API?

**Comment by mpadge** [comment]
Because `osmdata` uses three kinds of labels, all of which are entirely consistent with and permitted by R, and all of which are essential to maintaining *and using* the inter-relationships within and between OSM data themselves:

1. Names on `sf$geometry` list items - these could be removed and replaced with a column;
2. Names on sub-items of `sf$geometry` lists, for `multi-line/polygon` objects; and
3. Rownames on the component matrices of all `sf$geometry` lists, which can not be removed for the same reason.

While the first of these could be removed, with labels stored as an additional (`sf`) data column, none of them can be removed without removing inter-relationships between components that are necessary for full package functionality. The [`leaflet` (and therefore `mapview`) issues](https://github.com/rstudio/leaflet/issues/631) arise because of (3). The second is actually what causes the Stack Overlflow issue linked to above, and it's neither `dplyr` nor `ggplot` that are the cause, rather arises because of `base::do.call`:

``` r
library (osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright
library (sf)
#> Linking to GEOS 3.7.2, GDAL 3.0.1, PROJ 6.1.0
x <- 
    getbb("Geneva") %>% 
    opq()%>%
    add_osm_feature(key = "natural", value = "water") %>%
    osmdata_sf(quiet = FALSE)
g11 <- x$osm_multipolygons$geometry [[1]] [[1]]
vapply (names (g11), nchar, integer (1), USE.NAMES = FALSE)
#>  [1] 21324     8     9     9     9     9    17     8     9     8    19     8
#> [13]     8     8     8     9     9     9     8     9    19     9     9     9
#> [25]     9     9     9
y <- do.call (rbind, g11)
#> Error in do.call(rbind, g11): variable names are limited to 10000 bytes
```

<sup>Created on 2019-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This is an inconsistency in `do.call` alone, because there is nothing in `base::rbind` or R itself that prevents *rownames* from having any arbitrary length, yet `do.call` restricts the length of the names of its own list items to this length:
``` r
nm <- function (len = 10000)
    paste0 (sample (c (letters, LETTERS), size = len, replace = TRUE),
            collapse = "")
n <- 20000
a <- matrix (runif (2), nrow = 1)
rownames (a) <- nm (n)
b <- matrix (runif (2), nrow = 1)
rownames (b) <- nm (n)
ab <- rbind (a, b)
nchar (rownames (ab))
#> [1] 20000 20000
# -> no problem having huge rownames of R objects

x <- list (a = a, b = b)
names (x) <- c (rownames (a), rownames (b)) # no problem giving huge names to list items
ab2 <- do.call (rbind, x) # problem!
#> Error in do.call(rbind, x): variable names are limited to 10000 bytes

names (x) <- NULL
ab3 <- do.call (rbind, x)
rownames (ab3) <- c (rownames (a), rownames (b))
identical (ab, ab3)
#> [1] TRUE
```

<sup>Created on 2019-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## conclusion

`do.call` has to be used more carefully, and/or modified to be consistent with naming conventions of base R.

**Comment by edzer** [comment]
You're diverting my argument. My point is that `osmdata` creates so-called `sf` objects that don't play with the rest of the `sf` ecosystem, and that do you this knowingly, on purpose, without warning users for downstream problems when using these objects, while leaving the burden or trouble shooting to others. My suggestion is to have `osmdata` either:

* create the objects as you do now, but give them different class labels, with the possibility of converting them to proper (unnamed/unlabeled) `sf` or `sfc` objects to make the difference clear and provide interoperability, or
* create compliant `sf` objects, by putting all the label stuff in other (attribute) columns or list-columns but not in the geometry.

**Comment by espinielli** [comment]
I have tried the proposed solution from https://stackoverflow.com/a/62032713/963575 using `osmdata::unname_osmdata_sf()` in 0.1.3.
Here is how it fails:

```
> lake_gva_sf <- lake_gva %>% 
   unname_osmdata_sf()
Loading required namespace: sf
Error in FUN(X[[i]], ...) : is.numeric(x) is not TRUE
```

**Comment by Robinlovelace** [comment]
Thanks for the report @espinielli. Could you provide a fully reproducible example? That could help test potential solutions.

**Comment by mpadge** [comment]
Yep, I can confirm that error too. Re-opening here and shall close with a fix. Thanks @espinielli

**Comment by mpadge** [comment]
Oh, actually already fixed. The error appears with current CRAN version 0.1.3, but does not with current dev version of >= 0.1.3.11.
