### ISSUE TITLE
getbb() keeps failing even though the query resolves in browser

### ISSUE THREAD

**Issue by stragu** [ropensci/osmdata#192]
In the last few days, I haven't been able to get a bounding box out of a `getbb()` command, even though the query URL resolves fine in a browser.

My example code is this one:

```r
uqbb <- getbb("University of Queensland",
            featuretype = "amenity:university",
            format_out = "sf_polygon")
```
In the console feedback, I get a combination of "HTTP2 framing layer" errors, and "REFUSED_STREAM (err 7)" errors.

Here is an example of the output I get until it fails:

```
Error in curl::curl_fetch_memory(url, handle = handle): Error in the HTTP2 framing layer
Request failed [ERROR]. Retrying in 1.4 seconds...
Request failed [408]. Retrying in 1.7 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): Error in the HTTP2 framing layer
Request failed [ERROR]. Retrying in 7.9 seconds...
Request failed [408]. Retrying in 10.3 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): HTTP/2 stream 3 was not closed cleanly: REFUSED_STREAM (err 7)
Request failed [ERROR]. Retrying in 10.1 seconds...
Request failed [408]. Retrying in 39.2 seconds...
Nominatim did respond as expected (e.g. due to excessive use of their api).
Please try again or use a different base_url
The url that failed was:
https://nominatim.openstreetmap.org/?q=University%20of%20Queensland&featuretype=amenity%3Auniversity&polygon_text=1&format=json&limit=10
No polygonal boundary for University of Queensland
```

If the command fails with a final Nominatim overload, an object is still created, but it is not usable (i.e. the geometry only contains NA values). This leads to the following error when trying to query Overpass with it:

```
Error in check_for_error(doc) : General overpass server error; returned:
OSM3S ResponseThe data included in this document is from www.openstreetmap.org. The data is made available under ODbL.Error: line 3: parse error: Unknown query clause Error: line 4: parse error: Unknown query clause Error: line 5: parse error: Unknown query clause 
```

The query that was created by `getbb()` is this one: https://nominatim.openstreetmap.org/?q=University%20of%20Queensland&featuretype=amenity%3Auniversity&polygon_text=1&format=json&limit=10
Opening it in a browser resolves without a problem.

My session info:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8       
 [4] LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] osmdata_0.1.1.009

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3      lattice_0.20-38 lubridate_1.7.4 crayon_1.3.4    packrat_0.5.0  
 [6] grid_3.6.1      R6_2.4.1        jsonlite_1.6    magrittr_1.5    pillar_1.4.2   
[11] httr_1.4.1      rlang_0.4.1     stringi_1.4.3   curl_4.2        rstudioapi_0.10
[16] sp_1.3-2        xml2_1.2.2      tools_3.6.1     stringr_1.4.0   compiler_3.6.1 
[21] pkgconfig_2.0.3 rvest_0.3.5     tibble_2.1.3  
```

**Comment by Robinlovelace** [comment]
This links to #191 and https://github.com/ropensci/osmdata/issues/191#issuecomment-553808685 in particular.

**Comment by mpadge** [comment]
Yeah, it is unfortunately caused by `nominatim` being rather flaky of late. The issued messages are an attempt to provide as much information as possible, and do clearly indicate what's going on - i.e., that the cause is nominatim and not `osmdata` itself. Not much we can do about that, sorry.

**Comment by stragu** [comment]
Thanks for the replies, but how come I can use the same query in the browser and get a JSON every single time? It never works with `getbb()`, but always works in the browser?

I propose this pull request, which solved my issue straight away: https://github.com/ropensci/osmdata/pull/193

I can now get bounding boxes without any issue with my fork, as consistently as before commit 86185db. Hope that helps!
