### ISSUE TITLE
Request Failed [404]

### ISSUE THREAD

**Issue by marcusyoung** [ropensci/osmdata#198]
I run the following:

```
opq("madrid") %>% 
  add_osm_feature("highway") %>% 
  osmdata_pbf(filename = "test.pbf")
```

And get: 
Request failed [404]. Retrying in 1.6 seconds...
Request failed [404]. Retrying in 1.4 seconds...

Nothing is downloaded.

**Comment by mpadge** [comment]
Hi Marcus, I think the pbf server is no longer active, or maybe it has moved? Either way, this issue is a good prompt for me to check and either update or retire that function

**Comment by mpadge** [comment]
@marcusyoung Confirming that there is no longer pbf support of any form via overpass, so the above commit retires and entirely removes the `osmdata_pbf()` function.

**Comment by marcusyoung** [comment]
Ok, that's a shame it was a useful feature.

**Comment by mpadge** [comment]
yep, sorry about that, but not much can be done, alas.
