### ISSUE TITLE
more flexible overpass queries

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#2]
Next request for cognitive input from @Robinlovelace and @hrbrmstr:

How are we going to construct overpass queries? Some food for thought in [`opq.R` here](https://github.com/osmdatar/osmdata/commit/aaa441f90de09178544a6fb185385aefd501063c), in which I've implement an option for non-exact matches. How far do we go aiding a user in avoiding the need to understand regex? I'd suggest a few simple extensions might actually go a long way in that regard, thereby making it easier to use for more people, but likely at the expense of requiring several additional arguments for `add_feature`.

A further issue: Many queries may not be constructed through sequential addition - prime example being `AND` rather than `OR` queries, because `AND` queries are not sequentially independent. (Consider that the example given in the [function `opq` here](https://github.com/osmdatar/osmdata/blob/master/R/opq.R) actually represents an `OR`-construction rather than an `AND`-construction.) And yet only `OR` queries are possible in the structure both of [`add_feature`](https://github.com/osmdatar/osmdata/blob/master/R/opq.R) and the `osmdatar` approach of specifying `extra_pairs` ([see lines 60-69 here](https://github.com/osmdatar/osmdata/blob/master/osmdatar/R/get-points.R)). 

I'd suggest that in addition to non-exact values, we could possibly implement further options for:
1. Negation
2. Match case or not? (This will be messy to implement, but possible)
3. Match position (maybe 0=start, 1=end, any other value = anywhere)
4. Accented characters - maybe could avoid an extra arg by simply replacing any such with wildcards?

This would leave only the task of dealing with proper `AND` queries, which requires a different approach to that of `add_feature`, which is unavoidably `OR`. Thoughts? Suggestions? Food for thought from this point of the [overpass language API](http://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide#Non-exact_names) onwards.

**Comment by Robinlovelace** [comment]
I'll try to put together some use cases. Where should these go? Point me to a wiki page and I'll populate when I have time (not till next week though maybe). Reproducible examples make everything so much clearer.

**Comment by mpadge** [comment]
Use cases are a great idea - you as a group owner should be able to start that wiki page yourself. There's no big rush on that one, it's just a desirable enhancement.

**Comment by mpadge** [comment]
I think this has been dealt with via #57
