### ISSUE TITLE
Request Failed [404] / General Overpass Error

### ISSUE THREAD

**Issue by ChrisWoodsSays** [ropensci/osmdata#200]
I'm getting the above error when trying to add features.

I've looked at issue [126](https://github.com/ropensci/osmdata/issues/126) and therefore tried loading the package from GitHub, but that has not helped.

I have full internet connectivity and am not sat behind a corporate firewall.

Any ideas?

`

    install.packages("osmdata")
    # devtools::install_github("ropensci/osmdata")
    library(osmdata)
    library(tidyverse)

    opq <- getbb("United Kingdom")%>%
        opq()

    coast <- opq %>%
      add_osm_feature(key = "natural", value = "coastline") %>%
      osmdata_sf()`

Gives the following output

Request failed [400]. Retrying in 1.3 seconds...
Request failed [400]. Retrying in 3.1 seconds...
Error in check_for_error(doc) : General overpass server error; returned:
OSM3S ResponseThe data included in this document is from www.openstreetmap.org. The data is made available under ODbL.Error: line 3: parse error: Unknown query clause Error: line 4: parse error: Unknown query clause Error: line 5: parse error: Unknown query clause

**Comment by stragu** [comment]
Hi @ChrisWoodsSays 

I get an empty bounding box (`NA NA NA NA`) when getting it with

```r
bb <- getbb("United Kingdom")
```

That's probably because the default `featuretype` is "settlement".

You can get the actual bounding box with:

```r
bb <- getbb("United Kingdom", featuretype = "country")
```

However, I think the query might be too big. With the following:

```r
coast <- bb %>%
  opq() %>% 
  add_osm_feature(key = "natural", value = "coastline") %>%
  osmdata_sf()
```
I get the following error:

```
Error in check_for_error(doc) : General overpass server error; returned:
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL. runtime error: Query timed out in "query" at line 4 after 26 seconds. 
```
You can increase the timeout with the `timeout` argument:

```r
coast <- bb %>%
  opq(timeout = 50) %>% 
  add_osm_feature(key = "natural", value = "coastline") %>%
  osmdata_sf()
```

... but even 50 seconds didn't cut it. Feel free to try with more.
It seems to work with something smaller, like Malta's coastline:

```r
bb <- getbb("Malta", featuretype = "country")
coast <- bb %>%
  opq() %>% 
  add_osm_feature(key = "natural", value = "coastline") %>%
  osmdata_sf()
library(sf)
plot(st_geometry(coast$osm_lines))
```

Hope that helps!

**Comment by mpadge** [comment]
Further to the insights of @stragu, note that for coastlines that serve to define any kind of administrative boundaries, you're better off first visually inspecting the boundaries on `openstreetmap.org` to find exact names or IDs or whatever. What you're likely looking for is [this administrative boundary](https://www.openstreetmap.org/relation/62149), which as you see has a single OSM ID number of 62149. You can then use the `opq_osm_id` function to extract objects by their ID numbers:
``` r
library (osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
uk <- opq_osm_id (id = 62149, type = "relation") %>%
    opq_string () %>%
    osmdata_sf ()
uk
#> Object of class 'osmdata' with:
#>                  $bbox : 
#>         $overpass_call : The call submitted to the overpass API
#>                  $meta : metadata including timestamp and version numbers
#>            $osm_points : 'sf' Simple Features Collection with 38248 points
#>             $osm_lines : 'sf' Simple Features Collection with 929 linestrings
#>          $osm_polygons : 'sf' Simple Features Collection with 4 polygons
#>        $osm_multilines : NULL
#>     $osm_multipolygons : 'sf' Simple Features Collection with 1 multipolygons
```

<sup>Created on 2020-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

That's the entire polygon boundary of the UK in `sf` format. To proceed with analysing or visualising this, you'll then likely need to inspect sub-components of the main multipolygon relationship on openstreetmap.org to find OSM ID values of particular components. The ID values are then held both as names of the multipolygon list items, as well as in the `osm_id` columns of the sub-features (polygons, linestrings), so you can dissemble and reassemble as desired. Hope that helps! (And @ChrisWoodsSays feel free to close the issue if so).

**Comment by ChrisWoodsSays** [comment]
Thank you @stragu and @mpadge, that's really helpful and I will close the issue now.
