### ISSUE TITLE
Probably broken install of gdal (first time user here) Thank you

### ISSUE THREAD

**Issue by daluna1** [ropensci/osmdata#206]
Probably broken install of gdal at 'C:/PROGRA~1/QGIS3~1.4/apps/gdal2/bin/'
Error: package or namespace load failed for ‘getSpatialData’:
 .onLoad failed in loadNamespace() for 'getSpatialData', details:
  call: strsplit(sapply(drivers, function(x) {
  error: non-character argument
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  running command '"C:\Program Files\QGIS 3.4\apps\gdal2\bin\gdalinfo.exe" --version' had status 309
2: In FUN(X[[i]], ...) :
  running command '"C:/PROGRA~1/QGIS3~1.4/apps/gdal2/bin//gdalinfo" --formats' had status 309

**Comment by mpadge** [comment]
That does not, unfortunately, look like anything I can help with, but yes, I suspect you're right that your `gdal` installation is broken. Easiest solution in most such cases is to un- and re-install `gdal` and see whether that helps, which i guess in your case means doing that through `QGIS`. Or you could simply try un- and re-installing `sf` within R - I'd guess the re-install of that would currently fail? Either way, it's clearly not related to this package, so I'm going to close, but feel free to ask any further questions - or maybe ask via `sf` if the reinstall of that fails.
