### ISSUE TITLE
way not found

### ISSUE THREAD

**Issue by gdkrmr** [ropensci/osmdata#215]
The following query fails:

```
'area[name="Deutschland"][boundary=administrative][admin_level=2];
 rel(pivot);
 (._;>>;)->.bl;
 rel.bl[admin_level=4];
 out geom;' %>%
  osmdata_sf
```

with
```
Error in rcpp_osmdata_sf(doc) : way can not be found
```

**Comment by mpadge** [comment]
That's not an error with this package - try pasting your query into [overpass turbo](https://overpass-turbo.eu). It won't generate any errors, but when you look at the result (by clicking on the "Data" tab on the top right), you'll see this:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.56.2 b688b00f">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2020-04-06T16:46:02Z" areas="2020-04-06T15:33:02Z"/>
</osm>
```


That exact result can be re-generated as in the following `reprex`:
``` r
library (osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
q <- paste0('area[name="Deutschland"]',
            '[boundary=administrative][admin_level=2];',
            ' rel(pivot);',
            ' (._;>>;)->.bl;',
            ' rel.bl[admin_level=4];')
osmdata_xml (q, filename = "out.xml")
readLines ("out.xml")
#> [1] "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"                                                                             
#> [2] "<osm version=\"0.6\" generator=\"Overpass API 0.7.56.2 b688b00f\">"                                                     
#> [3] "  <note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>"
#> [4] "  <meta osm_base=\"2020-04-06T16:55:02Z\" areas=\"2020-04-06T16:40:02Z\"/>"                                             
#> [5] "</osm>"
```

<sup>Created on 2020-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So it's your query that is causing the error - for manual queries like that, it's always best to first use [overpass turbo](https://overpass-turbo.eu) to check if they work. Your query returns no data, and so the error makes perfect sense. Hope that helps!

**Comment by gdkrmr** [comment]
This is what I get:

![image](https://user-images.githubusercontent.com/12512930/78645326-ab821a00-78b7-11ea-87ed-c12179726472.png)

**Comment by mpadge** [comment]
Ah, i see, and also see that i missed the final `out geom` line in my code. But more importantly, you've got the line after `rel(pivot)` of:
```
(._;>>;)->.bl;
```
which collects the results of the `pivot` call into the object named `bl`.But then you follow that with 
```
rel.bl[admin_level=4];
out geom;
```
This expliictly selects the `rel` objects from `bl`, and outputs their geometries only. This is wrong, because an OSM data set must include not only the objects you want (in this case, `rel` objects), but also all information from their components. Your query returns data, but these are unusable by any software. For example, GDAL gives:
``` r
library (sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library (osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
q <- paste0 ('area[name="Deutschland"]',
             '[boundary=administrative][admin_level=2];',
             'rel(pivot);',
             '(._;>>;)->.bl;',
             'rel.bl[admin_level=4];',
             'out geom;')
#osmdata_xml (q, filename = "out.xml")
st_layers ("out.xml")
#> Driver: OSM 
#> Available layers:
#>         layer_name       geometry_type features fields
#> 1           points               Point       NA     10
#> 2            lines         Line String       NA      9
#> 3 multilinestrings   Multi Line String       NA      4
#> 4    multipolygons       Multi Polygon       NA     25
#> 5  other_relations Geometry Collection       NA      4
st_read ("out.xml", layer = "multipolygons")
#> Reading layer `multipolygons' from data source `/data/mega/code/repos/ropensci/osmdata/out.xml' using driver `OSM'
#> Simple feature collection with 0 features and 25 fields
#> bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
#> geographic CRS: WGS 84
st_read ("out.xml", layer = "points")
#> Reading layer `points' from data source `/data/mega/code/repos/ropensci/osmdata/out.xml' using driver `OSM'
#> Simple feature collection with 0 features and 10 fields
#> bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
#> geographic CRS: WGS 84
```

<sup>Created on 2020-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And all features (geometries) are `NA`. The main problem here is that you missed the necessary collector between those last 2 lines:
```
rel.bl[admin_level=4];
(._;>;);
out geom;
```
That *should* collect all necessary data, although note that even that may not always work. The only `out` command guaranteed to work, whether via `osmdata` or `sf/GDAL` is `out body`, as described in the [wiki](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#out)

> Allowed values, in any order, are:
> ...
> body: Print all information necessary to use the data.

The key there is "*to use the data*". Lots of the other `out` options will generate data, but with no necessary guarantee that those will able to be subsequently used by any particular software. This works:
``` r
setwd ("/data/mega/code/repos/ropensci/osmdata")
library (osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
q <- paste0 ('area[name="Deutschland"]',
             '[boundary=administrative][admin_level=2];',
             'rel(pivot);',
             '(._;>>;)->.bl;',
             'rel.bl[admin_level=4];',
             '(._;>;);',
             'out body;')
osmdata_xml (q, filename = "out.xml")
x <- osmdata_sf (q, doc = "out.xml", quiet = FALSE)
#> converting OSM data to sf format
x
#> Object of class 'osmdata' with:
#>                  $bbox : 
#>         $overpass_call : The call submitted to the overpass API
#>                  $meta : metadata including timestamp and version numbers
#>            $osm_points : 'sf' Simple Features Collection with 284795 points
#>             $osm_lines : 'sf' Simple Features Collection with 4126 linestrings
#>          $osm_polygons : 'sf' Simple Features Collection with 14 polygons
#>        $osm_multilines : NULL
#>     $osm_multipolygons : 'sf' Simple Features Collection with 16 multipolygons
```

<sup>Created on 2020-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The whole problem here was your query, and not the software. When constructing and working with custom `overpass` queries, it really is your reponsibility to ensure that your queries are correct.

**Comment by gdkrmr** [comment]
> When constructing and working with custom overpass queries, it really is your reponsibility to ensure that your queries are correct.

I get that overpass can return diverse outputs and that you cannot possibly support them all. Thanks for the help! Would parsing output from `out geom` be a feature request?

**Comment by mpadge** [comment]
My judgment call would be that the only safe way to guarantee functionality is to only parse output from `out body`. The results of `out geom` depend upon where that `geom` has been extracted from, and are inherently unpredictable. The core issue remains that OSM itself is constructed around a [data model](https://wiki.openstreetmap.org/wiki/Elements) that presumes every higher order object is described by component IDS, and each one of those lower-order components is also ***always*** included in a dataset. `out geom` can violate that principle; `out body` is guaranteed never to do that. So i don't see any scope at present for processing the results of `out geom`.

That said, you could look in to GDAL code, and discussions around that, to see whether there have been discussions of offering any such abilities. You could also maybe look in the code/issues of [`osmcode`](https://github.com/osmcode), especially things like [`osmcoastline`](https://github.com/osmcode/osmcoastline)? But note that most repos there extend from [`osmium`](https://github.com/osmcode/osmium-tool), which is strictly coded to only process planet dumps, or parts thereof, that are always guaranteed to be in the proper format.
