### ISSUE TITLE
[BUG] unname_osmdata_sf fails at unname_osm(x, "what=osm_multipolygons")

### ISSUE THREAD

**Issue by rgzn** [ropensci/osmdata#219]
The function `unname_osmdata_sf` throws an error when it calls the helper function `unname_osm` on for the multipolygon attribute of an osmdata sf object. The reprex I've included is just the error from the standard public functions in the package. 

Note: I did not include the layers.xml in this because I am using the example data provided on the README of the osmdata package. 

``` r
library(tidyverse)
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright

x <- opq(bbox = c(-0.27, 51.47, -0.20, 51.50)) %>% # Chiswick Eyot in London, U.K.
  add_osm_feature(key = 'name', value = "Thames", value_exact = FALSE) %>%
  osmdata_sf()
x %>% unname_osmdata_sf()
#> Loading required namespace: sf
#> Error in vapply(x, ncol, 0L): values must be length 1,
#>  but FUN(X[[1]]) result is length 0

packageVersion("osmdata")
#> [1] '0.1.3.3'
R.Version()$version.string
#> [1] "R version 3.6.1 (2019-07-05)"
#sessionInfo()
```

<sup>Created on 2020-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rgzn** [comment]
I think this is fixed by changing sf::st_polygon to sf::st_multipolygon .
Pull request: 
https://github.com/ropensci/osmdata/pull/220

**Comment by mpadge** [comment]
Absolutely right, and the perfect fix for it. Thanks for helping make the package more robust!
