### ISSUE TITLE
[BUG] set overpass url getting error Request failed 

### ISSUE THREAD

**Issue by dipenpatel235** [ropensci/osmdata#222]
**Steps to follow in reporting a bug with `osmdata`**

Please follow all of the following steps, and only submit once you've checked all boxes (where appropriate).

- [ ] Download data locally via `osmdata_xml(q, filename = "myfile.xml")` (where `q` is your query)
- [ ] Use the [`reprex` package](https://reprex.tidyverse.org/) to reproduce your bug, including a `setwd()` command at the start to ensure you are in the directory where you've downloaded your data
- [ ] Include comparison with equivalent results from the `sf` package using the code shown below
- [ ] Paste the result in the indicated section below
- [ ] Delete the `setwd()` line from the pasted result
- [ ] Include the output of both `packageVersion("osmdata")` and `R.Version()$version.string`
- [ ] Alternatively, include the full output of `sessionInfo()`

### Paste `reprex` output here

Please include the following lines:
``` r
library(osmdata)
Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
get_overpass_url()
[1] "https://overpass.kumi.systems/api/interpreter"
## for security purpose i have added dumy host name (my.osm.server) in below url 
new_url <- "https://my.osm.server/api/interpreter"
set_overpass_url(new_url)
Request failed [403]. Retrying in 1.3 seconds...
Request failed [403]. Retrying in 2.4 seconds...
Request failed [403]. Retrying in 1 seconds...
Request failed [403]. Retrying in 8.4 seconds...
Request failed [403]. Retrying in 24.5 seconds...
Request failed [403]. Retrying in 46.5 seconds...
Request failed [403]. Retrying in 49.3 seconds...

packageVersion("osmdata")
[1] ‘0.1.3’

 R.Version()$version.string
[1] "R version 3.4.4 (2018-03-15)"

> #sessionInfo()
>
```
Thanks! :smile:

**Comment by mpadge** [comment]
The `set_overpass_url()` function is only for very specific use cases, primarily to enable access to local servers like Ireland and Switzerland, as described in [the help file](https://docs.ropensci.org/osmdata/reference/set_overpass_url.html), or if you're trying to configure and use your own locally hosted overpass server. That help file also lists the possible servers which can be used, so there is no need for you to have entered a dummy name - it can only be one of the addresses listed there; any other values with cause the error that you're seeing. This function ought never be used for normal usage of this package.
