### ISSUE TITLE
[BUG] getbb does not return for place_name = "Buelach" if format_out = "polygon"

### ISSUE THREAD

**Issue by nfruehADA** [ropensci/osmdata#225]
Unfortunately I am unable to procude a reprex output since the function call does not return and hence no reprex output is generated. But it is very easy to reproduce, since it is only this line of code:
```
library(osmdata)
boundingPolygon <- osmdata::getbb(place_name = "Buelach", format_out = "polygon")
```
Buelach (or Bülach) is a medium-sized town in Switzerland which definitively exists. If `format_out` is dropped, the function works as it should. However with `format_out = "polygon"` it does not return. We tried this with a lot of different `place_names` and it only occured with this specific name (no matter if written Buelach or Bülach or Bulach).

Information about my system:
```
> packageVersion("osmdata")
[1] ‘0.1.3’
> R.Version()$version.string
[1] "R version 4.0.1 (2020-06-06)"
```
as well as (on a different machine)
```
> packageVersion("osmdata")
[1] ‘0.1.3’
> R.Version()$version.string
[1] "R version 3.6.3 (2020-02-29)"
```

**Comment by mpadge** [comment]
Thanks for finding that @nfruehADA - it was indeed a bug, and did indeed seem to time out. That commit has fixed. Thanks for helping to improve the package!

**Comment by nfruehADA** [comment]
Awesome! 👍

**Comment by mpadge** [comment]
Re-opening to remind me to add you to the "allcontributors" list on front page - check back when the issue closes, and you should see your contribution acknowledged and linked there.
