### ISSUE TITLE
Documentation: how to get trails in the USA

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/osmdata#227]
After seeing this [Tweet](https://twitter.com/shinysci/status/1311015092973113346) I'd thought it worth reproducing and it worked a charm. Reproducible code:

```r
library(osmdata)
library(sf)
library(spData)
usa = us_states

trails = opq(st_bbox(usa), timeout = 3600) %>%
  add_osm_feature(key = "network", value = "nwn") %>%
  osmdata_sf()
# waiting....
plot(trails$geometry)
```

**Comment by Robinlovelace** [comment]
![animation](https://user-images.githubusercontent.com/1825120/94681403-4ca7d580-031b-11eb-81b1-6d4588b034a7.gif)

Result... a bit time consuming but works!

**Comment by Robinlovelace** [comment]
Not really an issue, just opened it to show that it works great for this case and in case it's worth documenting somewhere in the docs.

**Comment by mpadge** [comment]
That is so good to see things just work out of the box so smoothly!! Feel free to drop lines in any documentation anywhere, or maybe even try to get this other guy in to contribute? (I can't find him on github or anywhere ...) Thanks!

**Comment by Robinlovelace** [comment]
Closing for now. Just wanted to document the code. Great to see it used!
