### ISSUE TITLE
[BUG] Error when trying to download cycleways

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/osmdata#233]
**Steps to follow in reporting a bug with `osmdata`**

Please follow all of the following steps, and only submit once you've checked all boxes (where appropriate).

- [ ] Download data locally via `osmdata_xml(q, filename = "myfile.xml")` (where `q` is your query)
- [ ] Use the [`reprex` package](https://reprex.tidyverse.org/) to reproduce your bug, including a `setwd()` command at the start to ensure you are in the directory where you've downloaded your data
- [ ] Include comparison with equivalent results from the `sf` package using the code shown below
- [x] Paste the result in the indicated section below
- [x] Delete the `setwd()` line from the pasted result
- [ ] Include the output of both `packageVersion("osmdata")` and `R.Version()$version.string`
- [ ] Alternatively, include the full output of `sessionInfo()`

### Paste `reprex` output here

Please include the following lines:
``` r
# <your reprex code here>

library(sf)
st_layers("myfile.xml") # give information on available layers
st_read("myfile.xml", layer = <desired_layer>)

packageVersion("osmdata")
R.Version()$version.string
#sessionInfo()
```

***If you are constructing or using a specialized `overpass` query***

- [ ] I have tried my query on [overpass-turbo.eu](https://overpass-turbo.eu), and it works
- [ ] I confirm that the data returned on [overpass-turbo.eu](https://overpass-turbo.eu) are identical to those returned from the equivalent call to `osmdata_xml(q, filename = "myfile.xml`)`.

Thanks! :smile:

Here is the code I tried:

```r
library(osmdata)
## Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
 
opq("England", timeout = 600) %>% 
  add_osm_feature(key = "highway", value = "cycleway") %>% 
  osmdata_sf(quiet = FALSE)
## Issuing query to Overpass API ...
Rate limit: 2
Query complete!
converting OSM data to sf format
Object of class 'osmdata' with:
                 $bbox : 49.674,-6.7047494,55.917,2.0919117
        $overpass_call : The call submitted to the overpass API
                 $meta : metadata including timestamp and version numbers
           $osm_points : 'sf' Simple Features Collection with 785559 points
            $osm_lines : 'sf' Simple Features Collection with 103479 linestrings
         $osm_polygons : 'sf' Simple Features Collection with 291 polygons
       $osm_multilines : NULL
    $osm_multipolygons : 'sf' Simple Features Collection with 1 multipolygons

> #> Issuing query to Overpass API ...
> #> Rate limit: 2
> #> Query complete!
> #> converting OSM data to sf format
> #> Error in rcpp_osmdata_sf(doc): Could not convert using R function: as.data.frame.
```

Will try to fill in the other checkboxes, just wanted to document this quickly.

**Comment by Robinlovelace** [comment]
Just to clarify, the data returned correctly, so unsure why it emitted the error message. Here's the result in any case, impressive!

![image](https://user-images.githubusercontent.com/1825120/109036408-780fd000-76c1-11eb-85cf-4505c423f286.png)

**Comment by mpadge** [comment]
Unfortunately i can't repeat that - all works for me without that error. I guess it would arise in one of the lines like [this](https://github.com/ropensci/osmdata/blob/main/src/osmdata-sf.cpp#L548-L549), but since i can't repeat it, maybe it was just a glitch in data delivery from overpass? Can you definitely repeat it? What happens if you try `osmdata_xml()` to download raw data, and then submit that as `doc` to `osmdata_sf()`?

**Comment by Robinlovelace** [comment]
Worked second time around as shown in perhaps be beefiest reprex I've ever run (impressive). Imagine 1st time there was a glitch on the network as you say. 

``` r
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
res = opq("England", timeout = 600) %>% 
  add_osm_feature(key = "highway", value = "cycleway") %>% 
  osmdata_sf(quiet = FALSE)
#> Issuing query to Overpass API ...
#> Rate limit: 0
#> Query complete!
#> converting OSM data to sf format
res
#> Object of class 'osmdata' with:
#>                  $bbox : 49.674,-6.7047494,55.917,2.0919117
#>         $overpass_call : The call submitted to the overpass API
#>                  $meta : metadata including timestamp and version numbers
#>            $osm_points : 'sf' Simple Features Collection with 785595 points
#>             $osm_lines : 'sf' Simple Features Collection with 103497 linestrings
#>          $osm_polygons : 'sf' Simple Features Collection with 291 polygons
#>        $osm_multilines : NULL
#>     $osm_multipolygons : 'sf' Simple Features Collection with 1 multipolygons
```

<sup>Created on 2021-02-25 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mpadge** [comment]
Gotta love a self-fixing bug :+1:
