### ISSUE TITLE
[BUG] `print.osmdata` returns NULL

### ISSUE THREAD

**Issue by odeleongt** [ropensci/osmdata#235]
**Using query from `osmdata_sf` help page since this issue is about how osmdata handles the objects, and not a problem with the data itself**

- [x] I have tried my query on [overpass-turbo.eu](https://overpass-turbo.eu), and it works
- [x] I confirm that the data returned on [overpass-turbo.eu](https://overpass-turbo.eu) are identical to those returned from the equivalent call to `osmdata_xml(q, filename = "myfile.xml`)`.

**Problem:** Using `print` on an object of class osmdata returns NULL.

**Expectation:** From the generic documentation I expect any print method to always return `x` from `print(x)`.

**Solution:** Add `return(x)` at the end of `print.osmdata` (after `message`).

Sample code:

```r
# Get data as suggested by osmdata documentation
hampi_sf <- opq("hampi india") %>%
    add_osm_feature(key="historic", value="ruins") %>%
    osmdata_sf()

# Not TRUE
identical(hampi_sf, print(hampi_sf))

# The object itself is fine
is.null(hampi_sf)
class(hampi_sf)

# Printing is what is wrong
is.null(print(hampi_sf))

# Common use case in piping -- returns NULL
hampi_sf <- opq("hampi india") %>%
    add_osm_feature(key="historic", value="ruins") %>%
    osmdata_sf() %>%
    is.null()
```

**Comment by mpadge** [comment]
Thanks @odeleongt, and yep, that would indeed be a :bug:. Do you want to submit a pull request that inserts that line and fixes? (As `invisible(x)`, rather than `return(x)`.) :+1:

**Comment by odeleongt** [comment]
Good catch! `invisible(x)` instead of `return(x)`. Done!
