### ISSUE TITLE
Filter imported .osm file for features

### ISSUE THREAD

**Issue by Suspicis** [ropensci/osmdata#239]
Dear creators, thank you very much for the great functionalities of your OSMDATA package!

After working with it for a while, I got a use case where I downloaded OSM data and safed it by the `osmdata_xml("myfile.osm")` comand. The downloaded data however is not filtered for any features by the `add_osm_feature()` command and therefore contains any kind of features.

> `q <- opq(bbox = 'Oslo') %>%`
> `osmdata_xml(filename = "myfile.osm")`

Now, when importing the .osm file again, I would like to filter for features, e.g. "highway", without doing another Overpass API request. Using the 

> `add_osm_feature("myfile.osm", key = "highway")`

 exhibits the following error code: 

> ## Error: $ operator is invalid for atomic vectors

Is there any possibility to filter for features of imported .osm data?

Thanks a lot for your reply!

**Comment by mpadge** [comment]
Thanks for asking @Suspicis. That is not really what the package is built for, as it intended to aid overpass queries which are themselves expected to request specific keys or key-value pairs. Nevertheless, if you want highways, one way within R would be to convert to `sf` with `osmdata_sf(doc = "myfile.osm")`, select the item you want, for example, `osm_lines`, and then just select the elements of that result according to the desired `key`, `key-value` pair, or whatever.

If you want to filter within the `.osm` data themselves without converting to some other format, then your best option would be to use [`osmium`](https://osmcode.org/osmium-tool/).
