### ISSUE TITLE
Build query using geometry type

### ISSUE THREAD

**Issue by AlbertRapp** [ropensci/osmdata#242]
Note that I have already asked this on [Stackoverflow](https://stackoverflow.com/questions/69123638/use-osmdata-package-in-r-to-find-objects-of-specific-geometry-type) but no one answered. So, at this point I am not so sure whether my request is currently possible and I just wasn't able to implement this or this functionality is really not available in the package.

I am trying to extract data like so:

```
extract_data <- function(bbx){
  highway_vals <- c("motorway", "trunk", "primary", "secondary")
  data <- bbx %>% 
    opq(timeout = 100) %>% 
    add_osm_feature(
      key = "highway", 
      value = highway_vals
    ) 
  
  data_of_interest <- list(osm_lines = data$osm_lines, osm_polygons = data$osm_polygons)
  data_of_interest
}
```
As you can see from this function, I am only really interested in the lines and polygons. Is there a way to put this restriction into the query? I already tried to look at `available_features()` but nothing fit the bill. Though, I have seen [here](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example#Find_multipolygons_with_more_than_one_outer_way_member_.28since_0.7.54.29) that in principle it should be possible to query by geometry such as "multipolygon".

Especially for large bounding boxes I will inevitably download a huge amount of points, i.e. there is always `data$osm_points` in the `data` variable after the query is executed. I believe that this wastes a huge amount of resources (at least the memory that is allocated to the variable `data` is way larger than the amount that is allocated to `data_of_interest`) and actually brings me to my download limit quite fast, i.e. I hit the `Please check /api/status for the quota of your IP address` error.

**Comment by mpadge** [comment]
[Answered on SO here](https://stackoverflow.com/a/69146073/8464209), which i hope provides a sufficient answer. Feel free to ask further questions there or here. Thanks!
