### ISSUE TITLE
[BUG] <internet connection error while having connection >

### ISSUE THREAD

**Issue by dmag-ir** [ropensci/osmdata#243]
**Steps to follow in reporting a bug with `osmdata`**

Please follow all of the following steps, and only submit once you've checked all boxes (where appropriate).

- [x] Download data locally via `osmdata_xml(q, filename = "myfile.xml")` (where `q` is your query)
- [ ] Use the [`reprex` package](https://reprex.tidyverse.org/) to reproduce your bug, including a `setwd()` command at the start to ensure you are in the directory where you've downloaded your data
- [ ] Include comparison with equivalent results from the `sf` package using the code shown below
- [x] Paste the result in the indicated section below
- [ ] Delete the `setwd()` line from the pasted result
- [ ] Include the output of both `packageVersion("osmdata")` and `R.Version()$version.string`
- [ ] Alternatively, include the full output of `sessionInfo()`

### Paste `reprex` output here
#Error: Overpass query unavailable without internet
Please include the following lines:
``` r

library(osmdata)    
tehran <- opq(bbox = 'Tehran, Iran') %>%
      add_osm_feature(key = 'admin_level', value = '9') %>% 
      osmdata_sf %>% 
      unique_osmdata 

#Error: Overpass query unavailable without internet

head(available_features())
#No internet connection


packageVersion("osmdata")
‘0.1.6.7’
packageVersion("sf")
‘1.0.2’

R.Version()$version.string
"R version 4.0.4 (2021-02-15)"
#sessionInfo()

R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 20

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.0 bit_4.0.4        compiler_4.0.4   magrittr_2.0.1   vroom_1.4.0      tools_4.0.4     
 [7] glue_1.4.2       crayon_1.4.1     bit64_4.0.5      lifecycle_1.0.0  rlang_0.4.11     purrr_0.3.4  
```

***If you are constructing or using a specialized `overpass` query***

- [ ] I have tried my query on [overpass-turbo.eu](https://overpass-turbo.eu), and it works
- [ ] I confirm that the data returned on [overpass-turbo.eu](https://overpass-turbo.eu) are identical to those returned from the equivalent call to `osmdata_xml(q, filename = "myfile.xml`)`.

Thanks! :smile:

**Comment by mpadge** [comment]
That error message comes from these lines:
https://github.com/ropensci/osmdata/blob/f638a318e2a43ecf4f69107c8e38af0be7a8f287/R/overpass-query.R#L161-L163

And similarly for `available_features()`:
https://github.com/ropensci/osmdata/blob/f638a318e2a43ecf4f69107c8e38af0be7a8f287/R/features.R#L18-L29

If `curll::has_internet()` fails, then so will any attempt to issue a query to the overpass server. The :bug: has nothing to do with this package, but happens because your R session is unable to connect. You'll have to look elsewhere to find a solution to that, which should hopefully be fairly straightforward. Thanks for using the package!
