### ISSUE TITLE
[BUG] <description of bug>

### ISSUE THREAD

**Issue by ischlo** [ropensci/osmdata#259]
Hello, I have faced an SSL error on my machine when trying to use the package lately. Any function calling the API would result in the following error message: 

Error in curl::curl_fetch_memory(url, handle = handle): SSL certificate problem: certificate has expired
Request failed [ERROR]. Retrying in 1 seconds...

Please include the following lines:
``` r
gettbb("Paris, France")
library(sf)

sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] osmdata_0.1.6 
```

Thanks for hinting me at a possible solution !

**Comment by Mashin6** [comment]
Works for me. Have you tried switching to different overpass instances? e.g. `set_overpass_url("https://overpass-api.de/api/interpreter")`

**Comment by mpadge** [comment]
Reasons are expanded in https://github.com/ropensci/osmdata/issues/243#issuecomment-924704935. It's unrelated to this package, and will resolve itself.

**Comment by ischlo** [comment]
Hi @mpadge, @Mashin6  , thanks for the quick reply
I thought so initially, but there no problem with the internet connection of the session and `curl::has_internet()` shows TRUE.  The problem first appeared several weeks ago as well, so it does not seem to resolve itself. 
@Mashin6 Your suggestion gives the same error message as mentioned in the original bug report.

**Comment by mpadge** [comment]
Sorry @ischlo, i put the wrong reference there - it's actually https://github.com/ropensci/osmdata/issues/224#issuecomment-962664370, and in particular [this link from that comment](https://letsencrypt.org/2021/10/01/cert-chaining-help.html). About the only thing you can directly do is to make sure your install of `openssl` is up to date (>= v1.1.0).
