### ISSUE TITLE
Fix pkgdown configuration for articles

### ISSUE THREAD

**Issue by maelle** [ropensci/osmdata#274]
We see

```
 Error in data_articles_index(pkg) : 
  Vignettes missing from index: query-split
```

To check everything is ok after editing the configuration file, run `pkgdown::check_pkgdown()`.

**Comment by mpadge** [comment]
Thank you!!!

**Comment by mpadge** [comment]
Oh, actually i already did that just the other day. Easy!

**Comment by maelle** [comment]
Oops sorry I should have checked the R-universe status! Thank you!!
