### ISSUE TITLE
extend tests

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#29]
Robin, This is something you could definitely help with! I'll take care of the `C++` coverage, but you could definitely extend the [`R` tests](https://codecov.io/gh/osmdatar/osmdata/tree/7b481627a45f366d52ce22604ae26b411618182d/R). One big advance will be an OSM example with a [multipolygon relation](http://wiki.openstreetmap.org/wiki/Relation:multipolygon) (that is, with `inner` and `outer` components), so if you can dig out a simple one for that, that'd be grand. That'd also be ideal for me to address #20.

(I don't think anything can be done about `stub.R, but will give that a ponder myself ...)

**Comment by Robinlovelace** [comment]
Sure - may not be until next week, or the weekend, for that - a busy week!

**Comment by mpadge** [comment]
No worries - still 3 weeks til milestone

**Comment by mpadge** [comment]
i've put in some [nifty `sf` tests](https://github.com/osmdatar/osmdata/blob/master/tests/testthat/test-sf-osm.R) which have greatly expanded coverage, and also serve the primary function of ensuring output is identical to direct `sf` output. The remaining tests should be trivial now

**Comment by mpadge** [comment]
Re-opening to add to upcoming project tasks while avoiding issue duplication.

**Comment by mpadge** [comment]
Lots more tests added between [this commit](https://github.com/ropensci/osmdata/commit/fd44a105de0db7f1c713d60c1ad78f7ee3ec5fb8) and [this one](https://github.com/ropensci/osmdata/commit/b355a5a3a0eab48b2524f4b542deea1190d2fcbc), so closing for now.
