### ISSUE TITLE
Current pull requests Dec 2022

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#292]
@jmaspons Can you please use this issue to briefly describe for each of your current pull requests:

- The general aim
- The order in which it should be merged - *that is especially important!*
- Any relationships/overlap with other PRs

Current PRs are: #285, #288, #289, #291.

Thanks!

---

## TODO

- [ ] #294 
- [ ] #295

## Done

- [x] #285
- [x] #288
- [x] #289 
- [x] #291

**Comment by jmaspons** [comment]
This set of PR add some options from overpassQL that osmdata didn't cover and some people find interesting (#179, #259, #269, and perhaps #252):

- Change the level of verbosity of the results by modifying the [out statement](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#out) (#288)
- Ask for [augmented differences](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Augmented-difference_between_two_dates_(adiff)) (#291) 

As some of the new results from the above options doesn't fit into spatial objects from `sf` et al., I want to implement a new function called `osmdata_data_frame` to get the results into a data.frame (#285). This is relevant for queries with `out tags;`, where no geometries are returned, or for `adiff` results which are not supported by the current osmdata_* functions.

As for #289 , it just a bug fix and tests to prevent them.

The order of the PRs doesn't matter. I would start by adding #285 which can be tested with xml files, and then add the extra options for `opq` which can use the `osmdata_data_frame` from the former PR to test the results. I've tried to split the PR in a logical and non overlapping way, but... let's see if or how the conflicts among branches appear 🤞 Hopefully the exhaustive tests will catch any drawback.

I'm not aware of any overlap with any open PR.

All in all, these PRs can be useful to inspect and correct the tags from OSM objects, to monitor changes and to help to localize `name:*` (eg. [adding `name:ca`](https://github.com/OSM-Catalan/toponimsCat)).

**Comment by jmaspons** [comment]
I have integrated all the branches successfully at my [dev branch](https://github.com/jmaspons/osmdata/tree/dev). So far, so good. I can make an all-in-one PR if you prefer so.

**Comment by mpadge** [comment]
No, thanks for the offer, but i think leaving them in smaller chunks will make the process easier to understand and manage. I'll merge as much as i can tomorrow. Thanks
