### ISSUE TITLE
[FEATURE] Allow queries with arbitrary object types

### ISSUE THREAD

**Issue by jmaspons** [ropensci/osmdata#293]
Would be nice to choose to query only relations or relations and ways.

I have a working implementation at https://github.com/jmaspons/osmdata/commit/b028105f22b1ce4b8d69b55551e2083c24bea87c

The new parameter `osm_types` to `opq` function can supersede the parameter `nodes_only` (could be deprecated). The patch will also simplify the code.

I can open a PR but perhaps is better to finish #292, I don't want to overwhelm you, @mpadge. I promise that I don't have more changes in mind... well, perhaps the out:csv thing and I will stop for a while  😋

**Comment by mpadge** [comment]
Yes, indeed, that would be nice. It's something that I've thought about too, but never got around to. I suggest we first deal with everything listed in #292, before moving on to this. Thanks!
