### ISSUE TITLE
[BUG] `osmdata_*` functions return features with changed tag names for tags with non-valid names

### ISSUE THREAD

**Issue by jmaspons** [ropensci/osmdata#301]
As per [make.names](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/make.names), valid syntactic names only include letters, numbers and the dot or underline characters and starts with a letter. For exemple, many keys in OSM contain also `:` which get transformed to `.`, then `name:ca` becomes `name.ca`

Non-valid names are not a big problem in R. Columns can be accessed anyway by ```df$`key:xx` ``` or `df[, "key:xx"]`. Name changes can be aboided with `data.frame(..., check.names=FALSE)`. I will try to make a PR if you agree with the behavior change.

**Comment by mpadge** [comment]
Yes indeed! I had this in mind recently. I was working directly from a local `.pbf`, converting filtered bits to `.osm`, and then reading with `osmdata_xml`. That yielded data.frames with intact `:` in names, but i ran into issues combining with other data generated in other ways which had converted `:` -> `.`.  I wrote a hacky work-around, but a proper solution would be better. And by "proper" i mean here ensuring that all OSM keys with `:` are ultimately retained and not converted to `.`. That'd be really cool, thanks!
