### ISSUE TITLE
[FEATURE] Split `get-osmdata.R` into several files

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#304]
@jmaspons Once we've merged your current PRs (#299, #302, #303), the `get-osmdata.R` file should be split into several smaller files. I suggest:

- `get-osmdata.R` (with only the minor helper functions)
- `get-osmdata-sf.R`
- `get-osmdata-sp.R`
- `get-osmdata-sp.R`
- `get-osmdata-df.R`
- `get-osmdata-meta.R`

But we can see what works best once we get that far. You may assign yourself here if you're keen to do that, otherwise I'll happily do it, and ask you to review.

**Comment by jmaspons** [comment]
Ok! I'll try after #299 is merged, which is ready. I can't assign myself for the task. Can you add me, @mpadge ?
