### ISSUE TITLE
align sf translation with osmium

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#36]
[osmium](http://osmcode.org/) implements its own translation of OSM into Simple Features [here](https://github.com/osmcode/libosmium/blob/master/include/osmium/geom/factory.hpp) - make sure that `osmdata` is compatible.

**Comment by Robinlovelace** [comment]
Wow that's very interesting. Notice it's C++ - does that mean it's easy to integrate and worth thinking about wrappers for some things? Over my head but @virgesmith I know will be interested to 'grok' another C++ codebase! We're working together in Leeds for the next 2 months at least btw so make good use of us although we're getting hammered on another project atm...

**Comment by mpadge** [comment]
Finally getting around to this, and it seems the issue can simply be closed as the interpretations are identical. The only real difference seems to be an ability for `osmium` to include a `direction` parameter which can be either `"forwards"` or `"backwards"`, with the latter allowing an `SF::LINESTRING` object to be encoded in the reverse direction to the OSM encoding. This is, however, not actually implemented and merely exists as a possibility in the code.
