### ISSUE TITLE
ropensci submission

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#41]
As far as I see things, `osmdata` is now largely done and includes functionality necessary for initial release. Only remaining tasks:

1. @Robinlovelace finish vignette
2. @masalmon once Robin's done that, `pkgbuild` the website again
3. [add examples to fn docs](https://github.com/osmdatar/osmdata/issues/35)

@hrbrmstr plan now is to submit this first to `ropensci` to gain some hopefully useful feedback prior to CRAN submission. Any comments, suggestions on general package structure at this stage? Or just a general nod of approval for us to go ahead and submit with you as package co-author?

Thanks all for all the help!

**Comment by Robinlovelace** [comment]
General nod of approval from me 👍

**Comment by masalmon** [comment]
Should `overpass` and `osmplotr` now have messages on loading to mention it's better to use `osmdata` now?

**Comment by mpadge** [comment]
`osmplotr` will integrate `osmdata` as soon as its on CRAN. And, @Robinlovelace , this means that the vignette should initially **not** contain a dedicated section on plotting, as this will be added in a second iteration. (Your current plot examples are fine for the moment, i'd say.) We'll just let the `ropensci` folk know that vignette descriptions of plotting will come later. `overpass` changes would be up to bob ...

**Comment by masalmon** [comment]
Btw @mpadge there was recently a rOpenSci review with comments on code compiling (see https://github.com/ropensci/onboarding/issues/92 Jeroen's comment) -- is this something that was checked for `osmdata`?

**Comment by mpadge** [comment]
Oh yeah, thanks heaps @masalmon - that actually generates loads of warnings that need addressing ...

**Comment by masalmon** [comment]
Cool/not cool, sorry I can't help!

**Comment by mpadge** [comment]
Just pointing me to that `ropensci` discussion was plenty help enough! I hadn't been doing any compile checks with `-Wall`, which equals ''Warnings ALL'', and is mega useful and mega important!

**Comment by mpadge** [comment]
A pre-submission pre-review review request for @Robinlovelace @masalmon : Suggested responses to the `ropensci` questions:

1. *What does the package do?* Extract OpenStreetMap (OSM) data as `sf` or `sp` objects. OSM data are extracted from the overpass API and processes with very fast C++ routines for return to R.

2. *Who is the target audience?* Anyone interested in geospatial analysis and visualisation

3. *Are there other R packages that accomplish the same thing? If so, what is different about yours?* The package is superficially identical to `GDAL` as implemented in `sf`, yet produces fundamentally different results, as briefly described in the main vignette, and detailed at length in a second vignette. `osmdata` also reproduces much functionality available in the CRAN package `osmar`, yet does so many orders of magnitude faster. Moreover, `osmar` only returns data defined by a bounding box, while the `osmdata` interface to the `overpass API` allows highly customised and specific queries to be constructed (see examples in vignette). `osmdata` is also designed to complement the `ropensci` package `osmplotr`, and the latter package will be modified immediately following CRAN acceptance of `osmdata`.

I've aired some further issues regarding potential publication on [OSF](https://osf.io/k752r/wiki/home/) - Maëlle: that's my suggested platform for Robin and I to discuss things not directly related to git work - it'd be great if you could also register there so we can all discuss publication(s) there. (Or feel free to suggest an alternative platform...)

**Comment by masalmon** [comment]
* We can create a Slack team :wink: I have the Slack app and :green_heart: Slack!

* When saying OSM data I think it'd be best to mention from which OSM APIs.

* In the overlapping section maybe mention that authors of `overpass` are authors of `osmdata` and that `osmar` doesn't seem to be developped anymore so `osmdata` really is the newest / best package. Maybe remind what `omsplotr` does exactly. I'm not sure I follow the `GDAL` comment, since `GDAL`/`sf` don't allow to retrieve OSM data?

* The target audience includes transport planners, urban planners, etc.

**Comment by mpadge** [comment]
Sure, :paintbrush: us in on a slack team and we can go from there ... (pending Robin's agreement)

Re: target audience - shall insert those

Re: overpass - that'll be taken care of in the author list.

Re: osmar - yeah, i'll definitely point out the cessation of dev there.

Re: GDAL/sf - yeah, it actually does allow OSM data to be retrieved, and in a sense functions *exactly* the same as `osmdata`, yet is also very different - see [second vignette](https://github.com/osmdatar/osmdata/blob/master/vignettes/osm-sf-translation.Rmd)

**Comment by masalmon** [comment]
@Robinlovelace when you agree please give me Mark's email address in an email :-)

**Comment by masalmon** [comment]
well IF you agree

**Comment by mpadge** [comment]
[here](https://github.com/mpadge)

**Comment by masalmon** [comment]
oh true I had forgotten about that. So I'll create a osmdatar team if Robin agrees.

**Comment by mpadge** [comment]
I'll be aiming to submit this week, and will do it as a simultaneous JOSS submission with authors ordered by lines of code contributed as:
myself, @hrbrmstr, @virgesmith, @Robinlovelace, @masalmon

@hrbrmstr - absent affirmation, i'll presume you're good with this. hope that's okay!

@virgesmith - a nod of assent, please!

**Comment by masalmon** [comment]
Awesome! I won't assign myself as an editor to this review 😀

Do you have ideas of reviewers to suggest?

**Comment by masalmon** [comment]
Maybe `osmar` authors?

**Comment by mpadge** [comment]
not sure. `osmar` was CRAN-ified in 2012 and not one thing has been done since, so i don't think they're particularly active. But luckily there's the might Jochen Topf (joto), author of `osmium` in all its wonderful glory. There'd be nobody better placed.

**Comment by Robinlovelace** [comment]
All sounds good to me, and re. slack I'm rob 00 x at gmail dot com (without whitespaces and with .s).

**Comment by masalmon** [comment]
Ok invites sent @mpadge @Robinlovelace (and anyone who wants to join just needs to send me their address)

**Comment by Robinlovelace** [comment]
@mpadge suggested answers (minor changes):

1. *What does the package do?* Download OpenStreetMap (OSM) data and convert to native R objects defined by `sf` or `sp` packages. OSM datasets are extracted from the overpass API and processed with efficient C++ routines.

2. *Who is the target audience?* Anyone interested in geospatial analysis and visualisation, especially geographers, transport modellers and planners.

3. *Are there other R packages that accomplish the same thing? If so, what is different about yours?* The package is similar to `GDAL` as implemented in `sf`, yet produces fundamentally different results, as briefly described in the main vignette, and detailed at length in a second vignette. `osmdata` also reproduces much functionality available in the CRAN package `osmar`, yet does so much faster and with a more intuitive user interface. `osmar` only returns data defined by a bounding box, while the `osmdata` interface to the `overpass API` allows highly customised and specific queries to be constructed (see examples in vignette). `osmdata` is also designed to complement the `ropensci` package `osmplotr`, and the latter package will be modified immediately following CRAN acceptance of `osmdata`.

**Comment by hrbrmstr** [comment]
thx for the extra ping :-)

I took a quick read-through on all the incredibly detailed, extra work you've done and am very thankful for your time, knowledge and craftsmanship. wish i cld have jumped in more to assist.

    permission <- TRUE

**Comment by mpadge** [comment]
one further question @hrbrmstr - what should we put as your affiliation?

**Comment by hrbrmstr** [comment]
Wish I cld get away with "The Avengers" or "Justice League" but "Rapid7" shld be cool :-)

**Comment by hrbrmstr** [comment]
Also, let me know when I can/should replace the `osmdata` repo/README with a link to this.

**Comment by mpadge** [comment]
@hrbrmstr Finally [on CRAN](https://cran.r-project.org/web/packages/osmdata/index.html)  - with many thanks to you and all others!

**Comment by virgesmith** [comment]
Well done!
I’m trying to get another package into CRAN as we speak, it’s a nightmare ☹

**Comment by mpadge** [comment]
i saw 'humanleague' cued up on CRAN incoming and wondering what hell that was - mighty impressed you've now claimed that name for eteRnity! Just a shame such a formerly astonishing band seems so enamored with mediocrity. Even nerdier than tracking musical refs in science papers: tracking musical refs in R packages. Now there's an opportunity ...
