### ISSUE TITLE
Characters are coerced into factors unnecessarily

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/osmdata#44]
This is unuseful, e.g.:

https://github.com/Robinlovelace/osmdata/commit/dad2fab178ce170232e2c5b14033dc263184857c#diff-c0aac139f53cce21e172492141a82bf3R465

Note I was forced to use `as.character()` - better if the data is stored as chars IMO.

**Comment by mpadge** [comment]
I totally agree with you, and [this commit](https://github.com/osmdatar/osmdata/commit/39a37642e0220b288cb544cd7fc6ef2787518713) kinda mostly fixes the issue by simply hiding it. These lines now work:
```
q0 <- opq("Seville")                                                                
q1 <- add_feature(q0, key = "highway", value = "cycleway")                          
cway_sev = osmdata_sf(q1)                                                           
id <- cway_sev$osm_lines$osm_id                                                     
cway_lines <- osm_lines (dat=cway_sev, id=id)                                       
```

The actual problem arises [here](https://github.com/Robinlovelace/osmdata/blob/master/R/get-osmdata.R#L127), yet these lines have to stay exactly as they are for complete `sf` compatibility. See Edzer's thoughts [here](https://github.com/edzer/sfr/issues/57) - factors are here to stay in the `sf` world.

**Comment by SymbolixAU** [comment]
Bringing this issue back to life

in [this line](https://github.com/ropensci/osmdata/blob/931dea3042e9c39905f9a6bebb0924a7fdb433ae/R/get-osmdata.R#L249) you hard-code `stringsAsFactors = TRUE`

```
    df <- if (length(x) == 1) # ONLY sfc
        data.frame(row.names = row.names)
    else # create a data.frame from list:
        data.frame(x[-sf_column], row.names = row.names,
                   stringsAsFactors = TRUE)
```

Could this argument be exposed to the user?

**Comment by SymbolixAU** [comment]
Can this also be exposed through [dodgr](https://github.com/ATFutures/dodgr/blob/master/R/streetnet-fns.R#L99) too?

**Comment by mpadge** [comment]
I've defaulted to current `sf` behaviour of `stringsAsFactors = FALSE`, so that propagates by extension to `dodgr`. Or did you mean something else?

**Comment by SymbolixAU** [comment]
oh yeah - my bad, I didn't make the connection. 👍
