### ISSUE TITLE
clarify distinction with OpenStreetMap package

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#59]
This should be done, notably in response to @edzer's [ropensci review of the package](https://github.com/ropensci/onboarding/issues/103). We just need to work out the best place / places to do it. cc @Robinlovelace @maelle

**Comment by maelle** [comment]
README + intro vignette?

**Comment by Robinlovelace** [comment]
Yes to @maelle's suggestions - any easy fix.

**Comment by mpadge** [comment]
All agreed then. I'll happily volunteer for [the harder issue](https://github.com/osmdatar/osmdata/issues/60), so it'd be great if one of you could take care of that

**Comment by maelle** [comment]
I can but from next week :-)

**Comment by mpadge** [comment]
no rush: i won't be able to anything more until at least the week after anyway. plus it seems we've still got another two reviews coming.

**Comment by maelle** [comment]
only one other review, right?
