### ISSUE TITLE
Broken link in vignette

### ISSUE THREAD

**Issue by karpfen** [ropensci/osmdata#64]
While looking through the [function reference](https://ropensci.github.io/osmdata/reference/), I saw that the page for [opq_to_string](https://ropensci.github.io/osmdata/reference/opq_to_string.html) is missing.

**Comment by Robinlovelace** [comment]
I've tried to fix it here but to no avail: https://github.com/ropensci/osmdata/pull/65

I'm getting this build error though:

```
> pkgdown::build_site()
Initialising site -----------------------------------------------------------------------------------------
Copying '/home/robin/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/jquery.sticky-kit.min.js'
Copying '/home/robin/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/link.svg'
Copying '/home/robin/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/pkgdown.css'
Copying '/home/robin/R/x86_64-pc-linux-gnu-library/3.4/pkgdown/assets/pkgdown.js'
Building home ---------------------------------------------------------------------------------------------
Updating README.md
Error: pandoc document conversion failed with error 67
> file.rename("R/opq_to_string.R", "R/opq_string.R")
```

**Comment by Robinlovelace** [comment]
I something failing in a previous function, e.g. `opq()`? @maelle @mpadge at my wits end on this one...

**Comment by mpadge** [comment]
Thanks Robin - I've fixed the first pandoc error, but am also getting this `opq()` fail thing. Will hopefully report back in a mo

**Comment by mpadge** [comment]
Nup, still fails for me. I even tried removing all `docs` (except the `./wiki` ones) and rebuilding afresh, but I just get
```
Building function reference ---------------------------------------------------
Error in osmdata - class : non-numeric argument to binary operator
```
I have no idea what that's trying to say - I even changed the class def to remove almost all binary operations, and it still occurs. @maelle - could you maybe please try `pkgdown::build_site()`-ing on your machine?

**Comment by mpadge** [comment]
I did a bit of a hack job by just removing the offending bits from the `_pkgdown.yml` - in this case, the lines for `osmdata-class`, `osmdata-package` and `osm-sf-translation`. Was then able to build the site, and then manually reconstruct it as if it still had these lines in it. There are probably some broken bits somewhere in there, but at least all function names and ref links appear to be correct.

Thanks @karpfen for reporting this one, thanks @Robinlovelace for getting on it so promptly. Might just keep the issue open until @maelle can hopefully give us a proper re-build on her ever-uncompromising windows beast.

**Comment by Robinlovelace** [comment]
Gr8 solution by the sounds of it : )

**Comment by mpadge** [comment]
yeah, the title bars of [both](https://ropensci.github.io/osmdata/articles/osmdata.html) [vignettes](https://ropensci.github.io/osmdata/articles/osm-sf-translation.html) are a disaster. Easy to manually fix, but better to do it all with a clean build

**Comment by maelle** [comment]
@mpadge @Robinlovelace I can build the website and will push as soon as I have access.

I was wondering whether both of you can knit vignettes and the README? Or is it pkgdown-specific?

**Comment by mpadge** [comment]
That's great - thanks @maelle! It was just `pkgdown`-specific (for me at least). Vignette builds were all okay. `pkgdown` is still a little flaky because on my ubuntu system it doesn't render the `cerulean` template properly - and i note that @Robinlovelace's new `pkgdown` page for [`stplanr`](https://ropensci.github.io/stplanr/) also seems to suffer the same issues. But it once again looks grand thanks maelle!

**Comment by maelle** [comment]
@Robinlovelace I can build your `stplanr` website if needed :wink:
