### ISSUE TITLE
A typo in the vignette

### ISSUE THREAD

**Issue by fzenoni** [ropensci/osmdata#66]
Hello,
I just found this great package in the UseR conference program, and digging into the vignette I found a small typo on this page: https://github.com/ropensci/osmdata/blob/master/vignettes/osmdata.Rmd.
There is one occurrence of `add_feeature()` that should be `add_feature()`.

**Comment by mpadge** [comment]
Thanks for the feedback and thanks for finding our little mistakes - feel free to send as a PR if you want

**Comment by mpadge** [comment]
[closed](https://github.com/ropensci/osmdata/commit/2613d8aab38a677c280dbf14111f56df694ad055)
