### ISSUE TITLE
Custom API

### ISSUE THREAD

**Issue by fzenoni** [ropensci/osmdata#68]
Is there a way to select a custom Overpass API, similarly to what is possible in osmar with the   `osmsource_api(url = "http://api.openstreetmap.org/api/0.6/")` function?

**Comment by mpadge** [comment]
Um, whoops - thanks for pointing that out! That functionality is kinda there, but it's buried in the now non-exported function [`overpass-query()`](https://github.com/ropensci/osmdata/blob/master/R/overpass-query.R#L90). This got switched somewhere along the line to default-only use of this value. I'll just have to re-insert this argument to the [`osmdata_xml/sp/sf()` functions](https://github.com/ropensci/osmdata/blob/master/R/get-osmdata.R), add appropriate documentation, and pass on through to `overpass_query()` and it'll work again.

As previously: PRs welcome if you want to give this a go

**Comment by fzenoni** [comment]
I've never contributed to any package before, so I guess there's always a first time :)
I will try, and let you know if I fail.

**Comment by mpadge** [comment]
Actually going to keep this issue open until this ability is described in the vignette

**Comment by fzenoni** [comment]
Maybe this isn't the end of the story. When I install the package from github and R tries to load the help box for any given function, I get this:
```
Error in fetch(key) : 
  lazy-load database 'C:/Users/fzenoni/Documents/R/win-library/3.4/osmdata/help/osmdata.rdb' is corrupt
```

**Comment by mpadge** [comment]
Not sure what that could be - maybe just a conflict as I was pushing to github or something? If it persists, then feel free to open another issue with full code to reproduce the problem.

**Comment by fzenoni** [comment]
My anxiety was unnecessary: reinstalling the package solved the issue. Thanks again.
