### ISSUE TITLE
pbf format

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#74]
@Robinlovelace @mem48 thanks for the heads up in #57. I had been ignoring this important issue, but it seems there's been a dev version online since late last year - see [this overpass git issue](https://github.com/drolbr/Overpass-API/issues/339). Looks like it's possibly through [`http://dev.overpass-api.de/test753/`](http://gis.19327.n8.nabble.com/PBF-output-prototype-available-for-testing-td5884534.html) - i'll have a go at it soon. I guess it'll be a fair bit of work (writing a whole new parser), but the speed up is likely to be well worth it.

**Comment by Robinlovelace** [comment]
Thanks for looking at it. I've got a branch that tries to support .pbf files via osmctools. Will open a bug I've found while testing on that.

**Comment by mpadge** [comment]
Awesome! The `overpass/test753` node works like a charm. A trial `pbf` is around 15% of the size of the equivalent `xml`, so download times should be correspondingly faster. Now i've just got to build the parser ...

**Comment by Robinlovelace** [comment]
Great stuff - see bodged approach via `osmconvert` - does not seem very fast though and adds a huge dependency so would not recommend you merge that #76

**Comment by mpadge** [comment]
It's still going to need the google `protobuf` (C++) library, but that should be easy. I've had a read through, and it should definitely be much faster - they claim 20-100 times the speed of XML see "Why not XML" [here](https://developers.google.com/protocol-buffers/docs/overview). It'll be a huge advance once it's done, just a bit of a frightening slog getting there, but i'll be learning loads doing it.

**Comment by Robinlovelace** [comment]
Great - seems relevant to this which I remember reading ages ago - curious why I've seen less of this package since then: https://cran.r-project.org/web/packages/RProtoBuf/vignettes/RProtoBuf-intro.pdf

**Comment by mpadge** [comment]
This enables you to directly download a `.pbf` to disk. I suppose I could implement that straight away, even though we can't yet do anything with it.
```
q <- opq (bbox = bbox) %>% add_feature (key = 'highway')                        
q$prefix <- gsub ("xml", "pbf", q$prefix)                                       
q$suffix <- gsub ("body", "meta", q$suffix)                                     
overpass_url <- 'http://dev.overpass-api.de/test753/interpreter'
pbf <- httr::POST (overpass_url, body = opq_string (q)) %>%
       httr::content (res, as = 'raw')
 ```

**Comment by mpadge** [comment]
now implemented as [`osmdata_pbf()`](https://github.com/ropensci/osmdata/commit/22f391098bfb811d2684100803d7cb4fb115a7f5) so at least we can get it straight to disk.

**Comment by Robinlovelace** [comment]
Fantastic progress, from Belgium j'imagine!

**Comment by Robinlovelace** [comment]
What's the status of this? `osmdata_pbf()` seems like a solution. Note tested it though. Will be amazing if/when it works.

**Comment by mpadge** [comment]
I need to find time to do it. I was trying to get it all via [`protozero`](https://github.com/mapbox/protozero), but that's a fairly big task so I might just take an easier road and use the standard google protobuf headers. That should be reasonably quick.

**Comment by Robinlovelace** [comment]
Just tested this and still seems there are issue, see reprex below:

```
opq("leeds") %>% 
  add_osm_feature("highway", "cycleway") %>% 
  osmdata_pbf(filename = "test.pbf")
```

It downloads something, but not a valid .pbf file as far as I can tell - a file with only 843 B.

**Comment by Robinlovelace** [comment]
I got the same tiny file size for all the cycleways in Leeds as all the residential roads in Leeds so not sure that it is valid. Tried to read-in to no avail. Can you reproduce with this command? 

```
opq("leeds") %>% 
  add_osm_feature("highway", "residential") %>% 
  osmdata_pbf(filename = "test.pbf")
```

**Comment by mpadge** [comment]
I get 404 errors, so maybe the server isn't even online at present? Or at all anymore? I should just tweak the code to prevent the function saving anything in these cases.

**Comment by mpadge** [comment]
@Robinlovelace FYI There is no overpass pbf API anymore, so that commit removes the `osmdata_pbf()` function entirely. See comment [here](https://wiki.openstreetmap.org/wiki/Overpass_API/Installation#Software).
