### ISSUE TITLE
Error when using doc = large .osm file

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/osmdata#75]
The esoteric example strikes again:

```r
u = "http://download.geofabrik.de/europe/albania.osh.pbf"
download.file(u, "albania.osh.pbf")
msg = "osmconvert albania.osh.pbf >albania.osm")
system(msg)
osmdata_xml(input_file = "albania.osh.pbf", filename = "albania.osm")
q = add_feature(opq("Albania"), "highway")
albanian_roads = osmdata_sf(q, doc = "albania.osm")
## Error in strsplit(as.character(tstmp), " ")[[1]] : 
##   subscript out of bounds
```

**Comment by mpadge** [comment]
You're lucky - it just kills my computer. But i'm not sure that `osmconvert` produces exactly the same `XML` format as overpass delivers. Any divergence will be hugely problematic. Can you try the convert on a smaller file to see whether that works?

**Comment by Robinlovelace** [comment]
It's standard OSM xml format and displays fine in QGIS - not sure about smaller files - used Albania as a deliberately small country. Could try Wales or maybe event Lichtenstein!

**Comment by Robinlovelace** [comment]
Interesting: just failed in QGIS too.

![image](https://user-images.githubusercontent.com/1825120/27872456-c5978276-61a0-11e7-8fda-f21dcc0a5acc.png)

**Comment by Robinlovelace** [comment]
But there clearly is data there, even if it won't import into an sqlite db: 
![image](https://user-images.githubusercontent.com/1825120/27872585-22553850-61a1-11e7-9e9f-4fe8e819b5c0.png)

**Comment by mpadge** [comment]
#crap-internet-at-useR - it means I should be doing more sociable things i'd suspect. I'll get back onto this asap

**Comment by Robinlovelace** [comment]
:+1: :beers:

**Comment by Robinlovelace** [comment]
What's the verdict?

**Comment by mpadge** [comment]
yeah, no verdict. Was just hoping to quietly close that one to clean things up a bit. The bigger issue is the need to process large files in memory-size chunks. I thought about renaming and re-opening the issue, but would prefer to leave it closed because that ability won't be able to be implemented in any `sf` form, and will have to wait for `osmdata_sc()` via `silicate::SC()` forms. There's a lot of work to do before then. cc @mdsumner

**Comment by mdsumner** [comment]
Off topic somewhat, while I catch up ... Any luck using sf or GDAL directly? I get all empty geoms, is this a dead end?

```R
td <- tempdir()
u = "http://download.geofabrik.de/europe/albania.osh.pbf"
f <- file.path(td, "albania.osh.pbf")
read_pbf <- function(file) {
  layers <- sf::st_layers(file)$name
  setNames(purrr::map(layers, 
             ~sf::read_sf(file, .x)), layers)
}
x <- read_pbf(f)
purrr::map(x, nrow)  ## all zero

```

**Comment by mdsumner** [comment]
(and, what are the "osh" files, versus "osm"? - "shell"?)

fwiw, this works well  - I'll use it to explore if maybe vapour/silicate can be used to filter through the padding - (and don't worry, I understand the direct PBF approach will be the best!)

```R
td <- tempdir()
u = "http://download.geofabrik.de/europe/albania-latest.osm.pbf"
f <- file.path(td, basename(u))
download.file(u, f, mode = "wb")
read_pbf <- function(file) {
  layers <- sf::st_layers(file)$name
  setNames(purrr::map(layers, 
             ~sf::read_sf(file, .x)), layers)
}
x <- read_pbf(f)
purrr::map_int(x, nrow)
#          points            lines multilinestrings    multipolygons  other_relations 
#           56605            83145              123           112826              692 
purrr::map_int(x, ncol)
#          points            lines multilinestrings    multipolygons  other_relations 
 #             11               10                5               26                5 
```

**Comment by Robinlovelace** [comment]
Awesome work - looks promising!

**Comment by mpadge** [comment]
okay, I just managed to reproduce your original `subscript out of bounds` error. I'll let you know when I've solved that one...

**Comment by mpadge** [comment]
That commit fixes your original problem, plus another one that that fix revealed. The problem remains that these geofabrik data include full changelogs and `osmdata` does not yet handle those correctly. We're going to have to address that one down the line somewhere.

**Comment by Robinlovelace** [comment]
Yes. Not least because changelogs are useful for active transport research! Many thanks for the fix and glad the esoteric example yielded fruit, albeit of an unanticipated kind.

**Comment by Robinlovelace** [comment]
Many thanks for the fix btw - will take a look at how you did that.

**Comment by mpadge** [comment]
the original problem was a stupid one on my part. geofabrik files do not have a timestamp, which i simply did not anticipate.
