### ISSUE TITLE
next version (0.1)

### ISSUE THREAD

**Issue by mpadge** [ropensci/osmdata#83]
@Robinlovelace @maelle a heads-up that i've sketched out [this project](https://github.com/ropensci/osmdata/projects/1) to give things a bit of order. Addressing all the issues will make the package loads better, stronger, faster, leaner, but it's going to be a slog. Current project structure is largely based around notion of `v0.0.5` being the first easy pickings, the the big beast of `pbf` in `v0.1.0`, then a couple of collections of lesser issues in the following two iterations. Feel free to drag issues around to other places, suggest other structures, or add any kind of input you see fit. Thanks in advance! (And close this issue once you've both read it.)

**Comment by Robinlovelace** [comment]
Awesome work on the project management mission.

**Comment by maelle** [comment]
this looks great, I like the format of the milestones!

**Comment by mpadge** [comment]
Great, now that y'all know, i'll close this.
