### ISSUE TITLE
RStudio crashes when doing specific queries

### ISSUE THREAD

**Issue by fzenoni** [ropensci/osmdata#87]
Dear all,

When performing some specific query the full RStudio session crashes. This happens during the attempt to convert osmdata object into sp.
Here follows some minimal code to reproduce the issue.

```
library(osmdata)
library(magrittr)
library(dplyr)
library(sf)

region_of_interest <- "Madrid"
bbox_roi <- opq(bbox = region_of_interest)
admn_roi <- bbox_roi %>%
  add_feature(key = 'admin_level', value = '7') %>%
  osmdata_sf(quiet = FALSE)
city <- admn_roi$osm_multipolygons
q <- opq(bbox = st_bbox(city))
poi1 <- q %>% add_feature(key = 'amenity', value = 'arts_centre',
                          value_exact = FALSE) %>% osmdata_sf(quiet = FALSE)
```

**Comment by fzenoni** [comment]
You can have fun and also try the following:
```
poi2a <- q %>% add_feature(key = 'leisure') %>% osmdata_sf(quiet = FALSE)
poi2b <- q %>% add_feature(key = 'shop') %>% osmdata_sf(quiet = FALSE)
```
I also thought it was a good idea to display my ```sessionInfo()``` (it looks like loading ```dplyr``` was not necessary after all).

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.5-2      magrittr_1.5  osmdata_0.0.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12    lattice_0.20-35 lubridate_1.6.0 grid_3.4.1      R6_2.2.2        DBI_0.7         jsonlite_1.5    units_0.4-5    
 [9] httr_1.2.1      stringi_1.1.5   curl_2.7        sp_1.2-5        xml2_1.1.1      tools_3.4.1     udunits2_0.13   stringr_1.2.0  
[17] compiler_3.4.1  rvest_0.3.2
```

**Comment by mpadge** [comment]
Thanks Florian! I haven't managed to reproduce it yet, but note in the meantime that the latest dev version allows to you simplify your queries by returning bounding polygons directly (instead of just rectangular boxes). Instead of this:
```
admn_roi <- opq(bbox = "Madrid" %>%) %>%
    add_feature(key = 'admin_level', value = '7') %>%
    osmdata_sf(quiet = FALSE)
city <- admn_roi$osm_multipolygons
q <- opq(bbox = sf::st_bbox(city))
```
you can just
```
city <- getbb("madrid spain", format_out = "polygon")
```
In this case, "madrid" means lots of things, so this returns a list of matrices which can be simply plotted to work out which one you need. In this case the enclosing boundary of Madrid Comarcos (county) is
```
city <- city [[10]]
```

**Comment by mpadge** [comment]
please keep finding things like this @fzenoni! `osmdata` is written presuming OSM data to be always nicely formed and nicely behaved. It can only become more robust when people find examples that break it, which is what you just did. Your example should now run without problems:
```
> bp <- getbb ("madrid spain", format_out = "polygon") [[1]]
> q <- opq (c (min (bp [, 1]), min (bp [, 2]), max (bp [, 1]), max (bp [, 2])))
> q %>% add_osm_feature(key = 'amenity', value = 'arts_centre', value_exact = FALSE) %>%
    osmdata_sf(quiet = FALSE)
Object of class 'osmdata' with:
                 $bbox : 40.1989288330078,-4.19932270050049,40.9182777404785,-3.13047528266907
        $overpass_call : The call submitted to the overpass API
            $timestamp : [ Wed 4 Jul 2017 12:05:32 ]
           $osm_points : 'sf' Simple Features Collection with 548 points
            $osm_lines : 'sf' Simple Features Collection with 0 linestrings
         $osm_polygons : 'sf' Simple Features Collection with 38 polygons
       $osm_multilines : 'sf' Simple Features Collection with 0 multilinestrings
    $osm_multipolygons : 'sf' Simple Features Collection with 4 multipolygons
```
(Note that `polygon [[1]]` is the polygonal form of what the standard rectangle will *usually* return, while `polygon [[10]]` is the much larger (total) county area. What you had was the combined area of all municipalities within the larger Madrid county, which falls somewhere in between.)

**Comment by fzenoni** [comment]
Thanks a lot to you @mpadge !
Everything fell apart so spectacularly that I couldn't just keep it for myself. Indeed OSM data is more broken that I expected: I am spending hours cleaning out empty polygons from my datasets.
Also thank you for the polygonal boundary suggestion!
