### ISSUE TITLE
Error in rcpp_osmdata_sf(doc): Expecting a string vector: [type=NULL; required=STRSXP].

### ISSUE THREAD

**Issue by niklaas** [ropensci/osmdata#98]
The error above I get when using `osmdata_sf` while `osmdata_sp` works fine on the following query:

```
library(osmdata)
library(glue)

query <- glue('
[out:xml][timeout:10];
node["building"](53.5530202596279,9.98771200497636,53.5549897262444,9.99060899917011);
way["building"](53.5530202596279,9.98771200497636,53.5549897262444,9.99060899917011);
relation["building"](53.5530202596279,9.98771200497636,53.5549897262444,9.99060899917011);
(._;>);
out body;
')

tryCatch({
  ret <- osmdata_sf(query)
},
error = function(e) {
  cat(paste0("`osmdata_sf` returned an error: ", e))
  ret <- osmdata_sp(query)
})

ret
```

At the moment my workaround is to use `tryCatch` and convert the `osmdata` object containing `sp` objects to an `osmdata` object holding `sf` objects.

Initially I thought that the query itself is the problem. Since I realised that `osmdata_sp` works though, I assume that there's a bug in the converter implemented in C++.

**Comment by mpadge** [comment]
thanks @niklaas - that was a great catch! Problem was previous dealing with empty `data.frame` objects in the `C++` routines for `sp` vs `sf`. The `data.frame` structures in the `R` representations are actually quite different, and require distinct `C++` code for each case. In this case, the `data.frame` was empty (for the `osmdata$osm_lines`, or `sf$LINESTRING` objects), and I hadn't yet coded the `sf` version to appropriately handle this. Thanks for finding this bug! All works as expected now.

**Comment by niklaas** [comment]
You're more than welcome. I still owe you more detail on the other issue but at least I could provide some help here.

Another thing: When writing the transformer for `osmdata` objects containing `sp`s to `osmdata` objects holding `sf`s, I realised that you only declare a single class `osmdata`. You don't distinguish between the two types. Wouldn't it make sense to declare two classes `osmdata_sf` and `osmdata_sp` though? For my edge case I had to write a test that can distinguish between both types. However, implementing two distinct classes could complicate things...

**Comment by mpadge** [comment]
yeah, it's a tricky issue that one. What i've done is just use one class, and then simply test the class of the list items (`$osm_points` and so on). They are always either one or the other type, so the two types can be distinguished with a single extra line. I suppose I could readily add an additional, `osmdata_sf/sp` to the class definition? Actually, that would be a good idea - I'll do that and let you know.

**Comment by mpadge** [comment]
Implemented with the above commit - feel free to PR any future ideas that might occur to you. This extension of the class def is obviously a really good idea that i simply hadn't thought of until you pointed it out. Thanks!

**Comment by niklaas** [comment]
You're welcome. I will do so!
