### ISSUE TITLE
Let osmdata_xml accept query string

### ISSUE THREAD

**Issue by RoyalTS** [ropensci/osmdata#99]
This works:

    query_string <- '[out:xml];
    area["name"="District of Columbia"]->.boundaryarea;
    (
      node[leisure=park](area.boundaryarea);
      way[leisure=park](area.boundaryarea);
      relation[leisure=park](area.boundaryarea);
    );
      (._;>);
      out body;'
                           
    osmdata_sf(query_string)

This does not:

    > osmdata_xml(query_string)
    Error in opq$features : $ operator is invalid for atomic vectors

Would it be possible for `osmdata_xml()` to accept a query string rather than an `opq` object as well?

Alternatively, are there ways of pulling all parks in DC that I haven't yet discovered?

**Comment by mpadge** [comment]
good catch, thanks @RoyalTS! Both `osmdata_sf` and `osmdata_sp` did a few checks on the `q` argument that were missing in `osmdata_xml`. Now fixed.
